<?php
    $itemCount = count($this->attachments);
?>

<div id="block-<?php echo $this->blockId; ?>" class="full-width-css grid-y grid-margin-y small-padding-0 medium-padding-1 large-padding-2 region <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <div class="grid-x grid-margin-x flex-container align-spaced">
        <?php foreach ($attachments as $attachment): ?>
            <div class="item-listing-item max-image-height item resource flex-container flex-dir-column align-middle item-count-<?php echo $itemCount; ?> small-margin-bottom-1 medium-margin-bottom-2">
                <?php
                $item = $attachment->item();
                if ($item):
                    ?>
                    <?php
                    $title = $this->plugin('escapeHtml')($item->displayTitle());
                    $media = $attachment->media() ?: $item->primaryMedia();
                    if ($media):
                        $image = preg_match('/alt=""/', $this->thumbnail($media, $this->thumbnailType)) == 1 ? $item->linkRaw($this->thumbnail($media, $this->thumbnailType, ['alt' => $title])) : $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                        echo $image;
                    endif;
                    ?>
                    <div class="separator-center">
                        <?php $showTitleOption = $this->showTitleOption; ?>
                        <?php if ($showTitleOption == 'item_title'): ?>
                            <h3 class="margin-top-1"><?php echo $item->link($item->displayTitle()); ?></h3>
                        <?php elseif ($showTitleOption == 'file_name'): ?>
                            <h3 class="margin-top-1"><?php echo $media->displayTitle(); ?></h3>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php
                    $date = $item->value('dcterms:date');
                    if ($date):
                    ?>
                    <h3><small date><?php echo $date; ?></small></h3>
                <?php endif; ?>
                <?php
                    $origin = $item->value('curation:location');
                    if ($origin):
                    ?>
                    <h3><small origin><?php echo $origin; ?></small></h3>
                <?php endif; ?>
                    </div>
                <?php
                $caption = $attachment->caption();
                if ($caption):
                    ?>
                    <div class="caption padding-1 xlarge-padding-horizontal-2 xlarge-padding-horizontal-3 font-wide flex-child-grow grid-container"><?php echo $caption; ?></div>
                <?php endif; ?>

                <div class="text font-wide text-left">
                    <?php
                    $identifier = $item->value('dcterms:identifier');
                    if ($identifier):
                    ?>
                    <h3 class="h4 identifier"><small><?php echo 'Ref. ' . $identifier; ?></small></h3>
                    <?php endif; ?>
                </div>

            </div>
        <?php endforeach; ?>
    </div>
</div>