<?php
    $itemCount = count($this->attachments);
?>

<div class="full-width-css grid-x grid-margin-x flex-container align-spaced small-padding-0 medium-padding-1 large-padding-2">
    <?php foreach ($attachments as $attachment): ?>
        <div class="card item resource flex-container small-margin-bottom-1 medium-margin-bottom-2 medium-padding-1">
            <?php
            $item = $attachment->item();
            if ($item):
                ?>
                <?php
                $title = $this->plugin('escapeHtml')($item->displayTitle());
                $media = $attachment->media() ?: $item->primaryMedia();
                if ($media):
                    $image = preg_match('/alt=""/', $this->thumbnail($media, $this->thumbnailType)) == 1 ? $item->linkRaw($this->thumbnail($media, $this->thumbnailType, ['alt' => $title])) : $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                    echo $image;
                endif;
                ?>
                <div class="separator-center">
                    <?php $showTitleOption = $this->showTitleOption; ?>
                    <?php if ($showTitleOption == 'item_title'): ?>
                        <h3 class="margin-top-1"><?php echo $item->displayTitle(); ?></h3>
                    <?php elseif ($showTitleOption == 'file_name'): ?>
                        <h3 class="margin-top-1"><?php echo $media->displayTitle(); ?></h3>
                    <?php endif; ?>
                <?php endif; ?>
                <?php
                    $date = $item->value('dcterms:date');
                    if ($date):
                    ?>
                    <h3><small date><?php echo $date; ?></small></h3>
                <?php endif; ?>
                <?php
                    $origin = $item->value('curation:location');
                    if ($origin):
                    ?>
                    <h3><small origin><?php echo $origin; ?></small></h3>
                <?php endif; ?>
                </div>
            <?php
            $caption = $attachment->caption();
            if ($caption):
                ?>
                <div class="caption padding-1 xlarge-padding-2 xlarge-padding-horizontal-3 flex-child-grow"><?php echo $caption; ?></div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>