<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/annona.css'));
$this->headScript()->appendFile($this->assetUrl('js/annona.js'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');
$mediaDisplay = $this->themeSetting('media_display');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));

$fullWidthMainBlockContent = $this->resourcePageBlocks($item, 'full_width_main');
$fullWidthMainHasBlocks = $fullWidthMainBlockContent->hasBlocks();
$mainWithSidebarBlockContent = $this->resourcePageBlocks($item);
$mainWithSidebarHasBlocks= $mainWithSidebarBlockContent->hasBlocks();
$leftSidebarBlockContent = $this->resourcePageBlocks($item, 'left');
$leftSidebarHasBlocks = $leftSidebarBlockContent->hasBlocks();
$rightSidebarBlockContent = $this->resourcePageBlocks($item, 'right');
$rightSidebarHasBlocks = $rightSidebarBlockContent->hasBlocks();

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

// Iterate through the media associated with the item
// Define a base array of media types that should be handled by Octopus Viewer
$allowedMediaTypes = ['image/jpeg', 'image/png', 'application/pdf', 'youtube'];

// Iterate through the media associated with the item
foreach ($itemMedia as $index => $media) {
    // Get the media type (e.g., "image/jpeg", "application/pdf")
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    
    // Add a rule to dynamically handle media based on the renderer
    //if ($mediaRenderer === 'iiif_presentation') {
        // Add 'iiif' renderer to the allowedMediaTypes dynamically
    //    $allowedMediaTypes[] = 'iiif_presentation';
    //}
    if ($mediaRenderer === 'youtube') {
        // Add 'iiif' renderer to the allowedMediaTypes dynamically
        $allowedMediaTypes[] = 'youtube';
    }
}

?>

<div class="resource-title">
    <?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 2); ?>
    <h2 class="label"><?php echo $translate('Item'); ?></h2>
</div>

<div class="<?php echo ($showLayout == 'inline') ? 'inline' : 'stack'; ?>">
    <?php $this->trigger('view.show.before'); ?>

    <div class="full-width-main margin-bottom-2 xlarge-margin-bottom-3">
        <?php 
            if (in_array($mediaType, $allowedMediaTypes) || $mediaRenderer === 'youtube') {
            //Use Octopus Viewer for supported media types
                echo $this->octopusViewer()->forItem($item);
                echo $mediaRenderer;
                echo 'Octopus Rule Activated';
            } else {
                echo $media->render();
                echo 'Default Rule Activated';
                echo $mediaRenderer;
            }
        ?>
    </div>
</div>

    <?php if ($fullWidthMainHasBlocks): ?>
    <div class="full-width-main margin-bottom-2 xlarge-margin-bottom-3">
        <?php echo $fullWidthMainBlockContent->getBlocks(); ?>
    </div>
    <?php endif; ?>

    <?php if ($mainWithSidebarHasBlocks || $leftSidebarHasBlocks || $rightSidebarHasBlocks): ?>
    
    <?php 
    if ($leftSidebarHasBlocks && $rightSidebarHasBlocks) {
        $sidebarWidth = '3';
        $mainWidth = '6';
    } else {
        $sidebarWidth = '4';
        $mainWidth = '8';
    }
    ?>
    
    <div class="grid-x grid-margin-x margin-bottom-1 large-margin-bottom-2 xlarge-margin-bottom-3">
        <?php if ($leftSidebarHasBlocks): ?>
        <div class="left-sidebar cell medium-<?php echo $sidebarWidth; ?> margin-top-1 medium-margin-top-2 xlarge-margin-top-3">
            <?php echo $leftSidebarBlockContent->getBlocks(); ?>
        </div>
        <?php endif; ?>

        <?php if ($mainWithSidebarHasBlocks): ?>
        <div class="main-with-sidebar cell medium-<?php echo $mainWidth; ?> margin-top-1 medium-margin-top-2 xlarge-margin-top-3">
            <?php echo $mainWithSidebarBlockContent->getBlocks(); ?>
        </div>
        <?php endif; ?>

        <?php if ($rightSidebarHasBlocks): ?>
        <div class="right-sidebar cell medium-<?php echo $sidebarWidth; ?> dark-background margin-top-1 large-margin-top-0 padding-1 large-padding-2 xlarge-padding-3">
            <?php echo $rightSidebarBlockContent->getBlocks(); ?>
        </div>
        <?php endif; ?>
    </div>
    <?php endif; ?>

    <?php $this->trigger('view.show.after'); ?>
</div>
