<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');
$mediaDisplay = $this->themeSetting('media_display');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));

$fullWidthMainBlockContent = $this->resourcePageBlocks($item, 'full_width_main');
$fullWidthMainHasBlocks = $fullWidthMainBlockContent->hasBlocks();
$mainWithSidebarBlockContent = $this->resourcePageBlocks($item);
$mainWithSidebarHasBlocks= $mainWithSidebarBlockContent->hasBlocks();
$leftSidebarBlockContent = $this->resourcePageBlocks($item, 'left');
$leftSidebarHasBlocks = $leftSidebarBlockContent->hasBlocks();
$rightSidebarBlockContent = $this->resourcePageBlocks($item, 'right');
$rightSidebarHasBlocks = $rightSidebarBlockContent->hasBlocks();

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
?>

<div class="resource-title">
<?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 2); ?>
<h3 class="label"><?php echo $translate('Item'); ?></h3>
</div>



<div class="<?php echo ($showLayout == 'inline') ? 'inline' : 'stack'; ?>">
    <?php $this->trigger('view.show.before'); ?>
        

  <?php if ($embedMedia): ?>
  <?php if ($itemMedia): ?>
    <div class="padding-top-2 padding-bottom-3 medium-padding-top-4 medium-padding-bottom-4">
      <div class="grid-x" id="media-wrapper">
        <?php if ((count($itemMedia) > 1)): ?>
          <div class="cell medium-10">
            <div class="media-embeds">
              <div class="tab-content" id="mediaTabContent">
                <?php $panel_id = 1; ?>
                <?php foreach ($itemMedia as $media): ?>
                  <div class="tab-pane fade <?php echo ($panel_id == 1 ? ' show active' : ''); ?>"
                    id="media-<?php echo $panel_id; ?>" role="tabpanel" aria-labelledby="media-<?php echo $panel_id; ?>-tab">
                    <?php echo $media->render(); ?>
                  </div>
                  <?php
                  $panel_id++;
                endforeach;
                ?>
              </div>
            </div>
          </div>
          <div class="cell medium-1" id="media-sidebar">
            <ul class="nav align-items-center flex-md-column d-md-block" id="mediaTab" role="tablist">
              <?php $tab_id = 1; ?>
              <?php foreach ($itemMedia as $media): ?>
                <li class="nav-item p-md-0 mb-md-3" role="presentation">
                  <button
                    class="nav-link text-secondary border-0 shadow-sm rounded p-0<?php echo ($tab_id == 1 ? ' active' : ''); ?>"
                    id="media-<?php echo $tab_id; ?>-tab" data-bs-toggle="tab" data-bs-target="#media-<?php echo $tab_id; ?>"
                    type="button" role="tab" aria-controls="media-<?php echo $tab_id; ?>"
                    aria-selected="<?php echo ($tab_id == 1 ? 'true' : 'false'); ?>">
                    <?php echo $this->thumbnail($media, 'medium', ['class' => 'rounded img-fluid', 'alt' => $media->displayTitle(), 'title' => $media->displayTitle(), 'data-bs-toggle' => 'tooltip']); ?>
                  </button>
                </li>
                <?php
                $tab_id++;
              endforeach;
              ?>
            </ul>
            <button class="btn-arrow btnNext border-0 bg-transparent text-secondary d-none d-md-block mx-auto" type="button"
              aria-controls="mediaTabContent" aria-label="Next">
              <i class="fas fa-chevron-down" title="Next" aria-hidden="true">
              </i>
            </button>
          </div>
        <?php else: ?>
          <div class="col">
            <div class="media-embeds">
              <?php foreach ($itemMedia as $media): ?>
                <?php echo $media->render(); ?>
              <?php endforeach; ?>
            </div>
          </div>
        <?php endif; ?>
      </div>
    </div>
    <?php endif; ?>  
    <?php endif; ?>              




    <?php $this->trigger('view.show.after'); ?>
</div>