<?php
$this->htmlElement('body')->appendAttribute('class', 'page ' . $page->slug());
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
$pageType = $this->pageMetadata('type');
if ($activePage):
?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs()->setPartial('common/foundation-breadcrumbs'); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="breadcrumbs">
        <?php echo $nav->menu()->setUlClass('breadcrumbs')->renderSubMenu(); ?>
    </nav>
    <?php endif; ?>
<?php endif; ?>

<?php if ($pageType == 'home'): ?>
<div class="full-width-css">
    <?php echo 'this is the home page'; ?>
    <?php $this->trigger('view.show.before'); ?>
    <div id="blocks" class="blocks">
        <?php echo $this->content; ?>
    </div>
</div>
<?php elseif(empty($pageType)): ?>
    <?php $this->trigger('view.show.before'); ?>
        <div id="blocks" class="blocks">
    <?php echo $this->content; ?>
    </div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>