<?php

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *   Specific to the module version:
 *   - class (string)
 *   - title (string): deprecated alias of "alt_link_title"
 *   - url (string): deprecated, will be removed. Use "page", "caption", alt title, or original asset alt value instead.
 * @var array $assets Deprecated, alias of attachments.
 * @var string $heading
 * @var string $className
 * @var string $alignment
 */

// Note: this hero uses the classes and js of Twitter Bootstrap.
// The hero uses a random asset.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<div class="full-width-css grid-x grid-padding-x region-splash hero-two-col">

<?php if (!count($attachments)) return; ?>
    <?php $attachment = $attachments[array_rand($attachments)]; ?>
    <?php if (empty($attachment['asset'])) return; ?>
    <div class="hero-image image-full region-splash flex-container <?= $escapeAttr($attachment['class']) ?>" style="background-image:linear-gradient(rgba(0, 0, 0, 0.0), rgba(0, 0, 0, 0.4)),url(<?= $attachment['asset']->assetUrl() ?>);">
    </div>

    <div class="large-4 xlarge-3 align-center align-middle">
        <?php if (!empty($heading)) : ?>
            <div class="asset-heading flex-container region-splash"> 
                <h2 class="text-treatment-1"><?= $escape($heading) ?></h2>
            </div>
        <?php endif; ?>
    </div>

    <?php if ($attachment['caption']) : ?>
        <div class="asset-caption large-6 xlarge-7 flex-container align-middle align-center region-splash margin-bottom-0"> 
            <p class="text-treatment-1 padding-1 large-padding-2"><?= $attachment['caption'] ?></p>
            <?php $attachmentUrl = $attachment['page'] ? $attachment['page']->siteUrl() : $attachment['url']; ?>
            <?php if ($attachment['alt_link_title'] && $attachmentUrl) : ?>
                <a href="<?= $escapeAttr($attachmentUrl) ?>"><button class="btn knowmore"><?= $escape($attachment['alt_link_title']) ?></button></a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>