<?php

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *   Specific to the module version:
 *   - class (string)
 *   - title (string): deprecated alias of "alt_link_title"
 *   - url (string): deprecated, will be removed. Use "page", "caption", alt title, or original asset alt value instead.
 * @var array $assets Deprecated, alias of attachments.
 * @var string $heading
 * @var string $className
 * @var string $alignment
 */

// Note: this hero uses the classes and js of Twitter Bootstrap.
// The hero uses a random asset.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<div class="full-width-css grid-x region-splash">
    <?php if (!empty($heading)) : ?>
        <div class="flex-container region-splash"> 
            <h2><?= $escape($heading) ?></h2>
        </div>
    <?php endif; ?>

    <?php if (!count($attachments)) return; ?>
    <?php $attachment = $attachments[array_rand($attachments)]; ?>
    <?php if (empty($attachment['asset'])) return; ?>
    <div class="small-12 medium-8 xlarge-9">
        <div class="hero-image image-xlarge region-splash flex-container <?= $escapeAttr($attachment['class']) ?>" style="background-image:linear-gradient(rgba(0, 0, 0, 0.0), rgba(0, 0, 0, 0.4)),url(<?= $attachment['asset']->assetUrl() ?>);">
        </div>
    </div>

    <?php if ($attachment['caption']) : ?>
        <div class="small-12 medium-4 xlarge-3 flex-container align-middle align-center region-splash colour-scheme-4 text-treatment-2 margin-bottom-0"> 
            <h2 class="text-treatment-3 large-padding-2"><?= $attachment['caption'] ?></h2>
            <?php $attachmentUrl = $attachment['page'] ? $attachment['page']->siteUrl() : ($attachment['url'] ?? null); ?> 
            <?php if ($attachment['alt_link_title'] && $attachmentUrl) : ?>
                <a href="<?= $escapeAttr($attachmentUrl) ?>"><button class="btn knowmore"><?= $escape($attachment['alt_link_title']) ?></button></a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>