<?php

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *   Specific to the module version:
 *   - class (string)
 *   - title (string): deprecated alias of "alt_link_title"
 *   - url (string): deprecated, will be removed. Use "page", "caption", alt title, or original asset alt value instead.
 * @var array $assets Deprecated, alias of attachments.
 * @var string $heading
 * @var string $className
 * @var string $alignment
 */

// Note: this hero uses the classes and js of Twitter Bootstrap.
// The hero uses a random asset.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<?php if (!count($attachments)) return; ?>
<?php $attachment = $attachments[array_rand($attachments)]; ?>
<?php if (empty($attachment['asset'])) return; ?>

<div class="full-width-css gray-background region-splash">
    <div class="hero-image hero-image-fixed image-large region-splash flex-container <?= $escapeAttr($attachment['class']) ?>" style="background-image:linear-gradient(rgba(0, 0, 0, 0.0), rgba(0, 0, 0, 0.4)),url(<?= $attachment['asset']->assetUrl() ?>);">
        <?php if (!empty($heading)) : ?>
            <div class="grid-x hero-title-bottom align-bottom">
                <div class="hero-title">
                    <div class="grid-container">
                        <h1><?= $heading ?></h1>
                        <?php $attachmentUrl = $attachment['page'] ? $attachment['page']->siteUrl() : ($attachment['url'] ?? null); ?>
                        <?php if ($attachment['alt_link_title'] && $attachmentUrl) : ?>
                            <a href="<?= $escapeAttr($attachmentUrl) ?>"><button class="btn knowmore"><?= $escape($attachment['alt_link_title']) ?></button></a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <?php if ($attachment['caption'] !== ''): ?>
        <div class="hero-title-caption hero-image-fixed">
            <div class="grid-container">
                <h3 class="h5 caption padding-horizontal-1">
                    <?= empty($attachment['raw']) ? $attachment['caption'] : $escape($attachment['caption']) ?>
                </h3>
            </div>
        </div>
    <?php endif; ?>
</div>
