<?php

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *   Specific to the module version:
 *   - class (string)
 *   - title (string): deprecated alias of "alt_link_title"
 *   - url (string): deprecated, will be removed. Use "page", "caption", alt title, or original asset alt value instead.
 * @var array $assets Deprecated, alias of attachments.
 * @var string $heading
 * @var string $className
 * @var string $alignment
 */

// Note: this hero uses the classes and js of Twitter Bootstrap.
// The hero uses a random asset.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<?php if (!count($attachments)) return; ?>
<?php $attachment = $attachments[array_rand($attachments)]; ?>
<?php if (empty($attachment['asset'])) return; ?>

<div class="full-width-css <?php echo $className; ?>">
    <div role="banner" class="hero-image image-xlarge region-splash flex-container <?= $escapeAttr($attachment['class']) ?>" style="background-image:linear-gradient(rgba(0, 0, 0, 0.0), rgba(0, 0, 0, 0.6)),url(<?= $attachment['asset']->assetUrl() ?>);">
        <?php if (!empty($heading)) : ?>
            <div class="grid-container grid-x flex-grow align-self-middle">
                <div class="hero-title dark-background">
                    <h1><?= $heading ?></h1>
                    <?php if ($attachment['caption'] !== ''): ?>
                        <h2 class="h4 padding-1 medium-padding-top-2">
                            <?= empty($attachment['raw']) ? $attachment['caption'] : $escape($attachment['caption']) ?>
                        </h2>
                    <?php endif; ?>
                    <?php $attachmentUrl = $attachment['page'] ? $attachment['page']->siteUrl() : ($attachment['url'] ?? null); ?>
                    <?php if ($attachment['alt_link_title'] && $attachmentUrl) : ?>
                        <a href="<?= $escapeAttr($attachmentUrl) ?>"><button class="btn knowmore"><?= $escape($attachment['alt_link_title']) ?></button></a>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
