<div id="block-<?php echo $this->blockId; ?>" class="listing-cards region <?php echo $this->regionClass; ?> <?php echo $this->classes ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <?php if ($this->hasTitle): ?>
        <h2><?php echo $this->title; ?></h2>
    <?php endif; ?>
    <?php if ($this->hasIntroduction): ?>
        <div class='block-introduction'>
            <?php echo $this->introduction; ?>
        </div>
    <?php endif; ?>
    <?php if ($this->hasPages): ?>
    <div class="cards grid-x grid-margin-x grid-margin-y margin-vertical-1">
        <?php foreach($this->pages as $page): ?>
            <div class='card cell medium-6 large-4 radius bordered shadow'>
                <?php if ($page['hasEmbeddedBlocks'] && array_key_exists('representativeImage',$page['embeddedBlocks'])): ?>
                    <?php echo $page['embeddedBlocks']['representativeImage'][0]; ?>
                <?php endif; ?>
                <div class="card-divider align-center">
                <h3><a href='<?php echo $page['o:url']; ?>'><?php echo $page['o:title']; ?></a></h3>
                </div>
                <?php if ($page['hasEmbeddedBlocks'] && array_key_exists('byline',$page['embeddedBlocks'])): ?>
                    <?php echo $page['embeddedBlocks']['byline'][0]; ?>
                <?php endif; ?>
                <?php if ($page['hasEmbeddedBlocks'] && array_key_exists('excerpt',$page['embeddedBlocks'])): ?>
                    <?php echo $page['embeddedBlocks']['excerpt'][0]; ?>
                <?php endif; ?>
                <a class='button primary' href='<?php echo $page['o:url']; ?>'>View this page</a>
            </div>
        <?php endforeach ?>
    </div>
    <?php endif; ?>
</div>