<div class="<?php echo $this->alignmentClass . ' ' . $this->thumbnailType; ?> file">
    <div class="attachments">
<?php foreach($this->attachments as $attachment): ?>
    <div class="item resource max-image-height">
    <?php
    $item = $attachment->item();
    if ($item):
    ?>
        <?php
            $media = $attachment->media() ? : $item->primaryMedia();
            $mediaRenderer = $media->renderer();
            if ($media && $mediaRenderer !== 'iiif') :
                echo $media->render([
                'thumbnailType' => $thumbnailType,
                'link' => $link,
            ]);
            elseif ($media) :
                echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
            endif;
        ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <h3 class="h2"><?php echo $item->link($item->displayTitle()); ?></h3>
        <?php elseif ($showTitleOption == 'file_name'): ?>
        <h3 class="h2"><?php echo $media->displayTitle(); ?></h3>
        <?php endif; ?>
    <?php endif; ?>

    <?php
    $caption = $attachment->caption();
    if ($caption):
    ?>
        <div class="caption"><?php echo $caption; ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
    </div>
</div>