<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/annona.css')); 
$this->headScript()->appendFile($this->assetUrl('js/annona.js'));
?>

<div class="<?php echo $this->alignmentClass . ' ' . $this->thumbnailType; ?> file">
    <div class="attachments max-image-height">
    <?php foreach($this->attachments as $attachment): ?>
        <div class="item resource max-image-height">
        <?php
        $item = $attachment->item();
        if ($item):
        ?>
            <?php
                $media = $attachment->media() ? : $item->primaryMedia();
                $mediaRenderer = $media->renderer();
                if ($media && $mediaRenderer !== 'iiif') :
                    echo $media->render([
                    'thumbnailType' => $thumbnailType,
                ]);
                elseif ($media) :
                    echo $this->thumbnail($media, $this->thumbnailType);
                endif;
            ?>
            <div class="metadata">
            <?php $showTitleOption = $this->showTitleOption; ?>
            <?php if ($showTitleOption == 'item_title'): ?>
            <h2><?php echo $item->displayTitle(); ?></h2>
            <?php elseif ($showTitleOption == 'file_name'): ?>
            <h2><?php echo $media->displayTitle(); ?></h2>
            <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php
        $caption = $attachment->caption();
        if ($caption):
        ?>
            <div class="caption padding-1"><?php echo $caption; ?></div>
        <?php endif; ?>
        <div class="learn-more">
            <h2 class="hollow button medium warning"><?php echo $item->link("View full item"); ?></h2>
        </div>
    </div>
<?php endforeach; ?>
    </div>
</div>