<div id="homepage-splash" class="full-width grid-x grid-padding-x margin-bottom-1 small-order-0 medium-order-1 flex-container block-<?php echo $this->blockId; ?> region <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <div class="large-7 item-listing-image items">
        <?php foreach ($attachments as $attachment): ?>
            <?php
                $item = $attachment->item();
            ?>
            <div class="item resource slick-slide-preload">
                <?php if ($item):
                    $title = $this->plugin('escapeHtml')($item->displayTitle());
                    $media = $attachment->media() ?: $item->primaryMedia();
                    if ($media):
                        $image = preg_match('/alt=""/', $this->thumbnail($media, $this->thumbnailType)) == 1 ? $item->linkRaw($this->thumbnail($media, $this->thumbnailType, ['alt' => $title])) : $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                ?>
                        <figure>
                            <?php echo $image; ?>
                            <?php if ($attachment->caption()): ?>
                              <figcaption class="orbit-caption caption"><?php echo $attachment->caption(); ?></figcaption>
                            <?php endif; ?>
                        </figure>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
   

    <div class="large-5 grid-y grid-padding-y padding-1 medium-padding-2 small-order-1 medium-order-0 introduction title-area dark-background">
        <div class='flex-container flex-dir-column introductory-text'>
            <?php if (!empty($titleSlideTitle)): ?>
                <h2 class="h1 padding-bottom-1"><?php echo $titleSlideTitle; ?></h2>
            <?php endif; ?>
            <?php if (!empty($titleSlideIntro)): ?>
                <p class="padding-1-medium-up"><?php echo $titleSlideIntro; ?></p>
            <?php endif; ?>
        </div>
    </div>
</div>


