<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $html
 * @var string $divclass
 * @var string $heading
 */

$escape = $this->plugin('escapeHtml');
?>

<div class="full-width-css colour-scheme-1 <?= $this->escapeHtmlAttr($divclass) ?>">
    <div class="grid-x grid-container">
        <div class="page-header">
            <?php if (!empty($heading)): ?>
            <h2><?= $escape($heading) ?></h2>
            <?php endif; ?>
            <?= $html ?>
        </div>
    </div>
</div>