<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $html
 * @var string $divclass
 * @var string $heading
 */

$escape = $this->plugin('escapeHtml');
?>

<div class="full-width-css colour-scheme-4 padding-1 padding-vertical-2 medium-padding-2 large-padding-vertical-3 <?= $this->escapeHtmlAttr($divclass) ?>">
    <div class="grid-x grid-container">
        <div class="page-header">
            <?php if (!empty($heading)): ?>
            <h2><?= $escape($heading) ?></h2>
            <?php endif; ?>
            <div class="padding-vertical-1 medium-padding-vertical-2 large-padding-vertical-3">
                <?= $html ?>
            </div>
        </div>
    </div>
</div>