<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $html
 * @var string $divclass
 * @var string $heading
 */

?>
<?php if (empty($divclass)): ?>

<?php if (!empty($heading)): ?>
<h2><?= $this->escapeHtml($heading) ?></h2>
<?php endif; ?>
<?= $html ?>

<?php else: ?>

<div class="full-width-css background-colour-uom-footer padding-vertical-1 flex-container <?= $this->escapeHtmlAttr($divclass) ?>">
    <?php if (!empty($heading)): ?>
    <h2><?= $this->escapeHtml($heading) ?></h2>
    <?php endif; ?>
    <div class="padding-vertical-1 medium-padding-vertical-2 large-padding-vertical-3 lead">
        <?= $html ?>
    </div>
</div>

<?php endif; ?>