<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $html
 * @var string $divclass
 * @var string $heading
 */

$escape = $this->plugin('escapeHtml');
?>

<div class="full-width padding-vertical-1 flex-container <?= $this->escapeHtmlAttr($divclass) ?>">
    <div class="grid-x grid-container flex-container">
        <?php if (!empty($heading)): ?>
        <h2><?= $escape($heading) ?></h2>
        <?php endif; ?>
        <div class="padding-vertical-1 medium-padding-vertical-2 large-padding-vertical-3 lead">
            <?= $html ?>
        </div>
    </div>
</div>