<div class="grix-x grid-container">
    <?php if (!empty($heading)): ?>
        <div class="media-text-heading">
            <h3 class="h2 padding-vertical-1"><?= $heading ?></h3>
        </div>
    <?php endif; ?>
</div>
<div class="full-width-css medium-padding-horizontal-1 large-padding-horizontal-2 xlarge-padding-horizontal-3">
    <div class="col-container col-media-container medium-padding-1" data-target-region-id="<?php echo $this->targetID; ?>">
        <?php foreach ($attachments as $attachment): ?>
            <div class="item-showcase item-showcase-openseadragon item resource small-margin-bottom-1 medium-margin-bottom-2 text-center">
                <?php
                $item = $attachment->item();
                if ($item):
                    ?>
                    <?php
                $media = $attachment->media() ? : $item->primaryMedia();
                $mediaRenderer = $media->renderer();
                if ($media) :
                    echo $media->render([
                        'thumbnailType' => $thumbnailType,
                    ]);
                endif;
                ?>
                        <?php $showTitleOption = $this->showTitleOption; ?>
                        <?php if ($showTitleOption == 'item_title'): ?>
                            <div class="separator-center metadata">
                                <h3 class="margin-top-1"><?php echo $item->link($item->displayTitle()); ?></h3>
                            </div>
                        <?php elseif ($showTitleOption == 'file_name'): ?>
                            <div class="separator-center metadata">
                                <h3 class="margin-top-1"><?php echo $media->displayTitle(); ?></h3>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php
                $caption = $attachment->caption();
                if ($caption):
                    ?>
                    <div class="caption padding-1 grid-container text-left"><?php echo $caption; ?></div>
                <?php endif; ?>
                <div class="learn-more">
                    <h3 class="button medium warning"><?php echo $item->link("Learn more about this item"); ?></h3>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>