<div id="block-<?php echo $this->blockId; ?>" class="full-width-css col-container col-media-container medium-padding-1" data-target-region-id="<?php echo $this->targetID; ?>">
    <?php foreach ($attachments as $attachment): ?>
        <div class="max-height item resource small-margin-bottom-1 medium-margin-bottom-2 text-center">
            <?php
            $item = $attachment->item();
            if ($item):
                ?>
                <?php
                $title = $this->plugin('escapeHtml')($item->displayTitle());
                $media = $attachment->media() ?: $item->primaryMedia();
                if ($media):
                    $image = preg_match('/alt=""/', $this->thumbnail($media, $this->thumbnailType)) == 1 ? $item->linkRaw($this->thumbnail($media, $this->thumbnailType, ['alt' => $title])) : $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                    echo $image;
                endif;
                ?>
                    <?php $showTitleOption = $this->showTitleOption; ?>
                    <?php if ($showTitleOption == 'item_title'): ?>
                        <div class="separator-center">
                            <h3 class="margin-top-1"><?php echo $item->link($item->displayTitle()); ?></h3>
                        </div>
                    <?php elseif ($showTitleOption == 'file_name'): ?>
                        <div class="separator-center">
                            <h3 class="margin-top-1"><?php echo $media->displayTitle(); ?></h3>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
                <?php
                $date = $item->value('dcterms:date');
                if ($date):
                ?>
                <h3 class="text-center"><small date><?php echo $date; ?></small></h3>
            <?php endif; ?>
            <?php
                $origin = $item->value('curation:location');
                if ($origin):
                ?>
                <h3 class="text-center"><small origin><?php echo $origin; ?></small></h3>
            <?php endif; ?>

            <?php
            $caption = $attachment->caption();
            if ($caption):
                ?>
                <div class="caption padding-1 font-wide grid-container text-left"><?php echo $caption; ?></div>
            <?php endif; ?>

            <div class="text font-wide text-center">
                <?php
                $identifier = $item->value('dcterms:identifier');
                if ($identifier):
                ?>
                <h3 class="grid-container h4 identifier text-left"><small><?php echo 'Ref. ' . $identifier; ?></small></h3>
                <?php endif; ?>
            </div>

        </div>
    <?php endforeach; ?>
</div>