<?php
$siteSetting = $this->plugin('siteSetting');
$currentLocale = $this->siteSetting('locale') ?: 'en_US';
?>

<div id="block-<?php echo $this->blockId; ?>" class="full-width-css grid-y grid-margin-y margin-top-1 medium-margin-top-0 small-padding-0 medium-padding-1 large-padding-horizontal-2 background-colour-uom-footer region <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?> ">
    <div class="grid-x grid-margin-x flex-container align-spaced">
        <?php foreach ($attachments as $attachment): ?>
            <div class="item-showcase item resource flex-dir-column small-margin-bottom-1 medium-margin-bottom-2 background-colour-uom-footer">
                <?php
                $item = $attachment->item();
                if ($item):
                    ?>
                    <?php
                    $title = $this->plugin('escapeHtml')($item->displayTitle());
                    $media = $attachment->media() ?: $item->primaryMedia();
                    ?>
                    <div class="separator-center metadata">
                        <?php $showTitleOption = $this->showTitleOption; ?>
                        <?php if ($showTitleOption == 'item_title'): ?>
                            <h2 class="margin-top-1"><?php echo $item->displayTitle(); ?></h2>
                        <?php elseif ($showTitleOption == 'file_name'): ?>
                            <h2 class="margin-top-1"><?php echo $media->displayTitle(); ?></h2>
                        <?php endif; ?>
                    <?php endif; ?>
                    </div>
                    <div class="margin-top-1 medium-margin-top-2">
                        <?php
                        $caption = $attachment->caption();             
                        if ($caption):
                            ?>
                            <div class="caption grid-container margin-bottom-1 medium-margin-bottom-2"><?php echo $caption; ?></div>
                        <?php endif; ?>
            <div class="learn-more">
                <?php if ($currentLocale == 'es'): ?>
                    <h2 class="button medium warning"><?php echo $item->link("Lea la descripción de la imagen"); ?></h2>
                <?php else: ?>
                    <h2 class="button medium warning"><?php echo $item->link("View full item"); ?></h2>
                <?php endif; ?>
            </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
