<div id="block-<?php echo $this->blockId; ?>" class="full-width-css grid-y grid-margin-y margin-top-1 medium-margin-top-0 small-padding-0 medium-padding-1 large-padding-horizontal-2 region <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?> ">
    <div class="grid-x grid-margin-x flex-container align-spaced">
        <?php foreach ($attachments as $attachment): ?>
            <div class="item-showcase item resource flex-dir-column small-margin-bottom-1 medium-margin-bottom-2 background-colour-uom-footer">
                <?php
                $item = $attachment->item();
                if ($item):
                    ?>
                    <?php
                    $title = $this->plugin('escapeHtml')($item->displayTitle());
                    $media = $attachment->media() ?: $item->primaryMedia();
                    ?>
                    <div class="separator-center metadata">
                        <?php $showTitleOption = $this->showTitleOption; ?>
                        <?php if ($showTitleOption == 'item_title'): ?>
                            <h2 class="margin-top-1"><?php echo $item->displayTitle(); ?></h2>
                        <?php elseif ($showTitleOption == 'file_name'): ?>
                            <h2 class="margin-top-1"><?php echo $media->displayTitle(); ?></h2>
                        <?php endif; ?>
                    <?php endif; ?>
                    </div>
                <?php
                $caption = $attachment->caption();
                if ($caption):
                    ?>
                    <div class="caption padding-1 xlarge-padding-horizontal-2 xlarge-padding-horizontal-3 flex-child-grow grid-container">
                        <p class="margin-bottom-0"><?php echo $caption; ?></p>
                    </div>
                <?php endif; ?>
                <div class="learn-more">
                    <h2 class="hollow button medium warning"><?php echo $item->link("View full item"); ?></h2>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
