<?php
    $itemCount = count($this->attachments);
?>

<div class="grix-x grid-container">
    <?php if (!empty($heading)): ?>
        <div class="media-text-heading medium-offset-1 large-offset-2">
            <h2 class="h2 padding-vertical-1"><?= $heading ?></h2>
        </div>
    <?php endif; ?>
</div>
<div class="full-width-css item-showcase-multiples grid-x grid-margin-x flex-container align-spaced small-padding-0">
    <?php foreach ($attachments as $attachment): ?>
        <div class="item-showcase card auto item item-count-<?php echo $itemCount; ?> resource flex-container flex-dir-column align-middlemargin-1 medium-margin-bottom-2">
            <?php
            $item = $attachment->item();
            if ($item):
                ?>
                <?php
                $title = $this->plugin('escapeHtml')($item->displayTitle());
                $media = $attachment->media() ?: $item->primaryMedia();
                if ($media):
                    $image = preg_match('/alt=""/', $this->thumbnail($media, $this->thumbnailType)) == 1 ? $this->thumbnail($media, $this->thumbnailType, ['alt' => $title]) : $this->thumbnail($media, $this->thumbnailType);
                    echo $image;
                endif;  
                ?>
                <div class="separator-center">
                    <?php $showTitleOption = $this->showTitleOption; ?>
                    <?php if ($showTitleOption == 'item_title'): ?>
                        <h2 class="margin-top-1"><?php echo $item->displayTitle(); ?></h2>
                    <?php elseif ($showTitleOption == 'file_name'): ?>
                        <h2 class="margin-top-1"><?php echo $media->displayTitle(); ?></h2>
                    <?php endif; ?>
                <?php endif; ?>
                </div>
            <?php
            $caption = $attachment->caption();
            if ($caption):
                ?>
                <div class="caption padding-1 xlarge-padding-2 xlarge-padding-horizontal-3 flex-child-grow"><?php echo $caption; ?></div>
            <?php endif; ?>
            <div class="learn-more">
                <h2 class="hollow button medium warning"><?php echo $item->link("Learn more about this item"); ?></h2>
            </div>
        </div>
    <?php endforeach; ?>
</div>