<?php
$siteSetting = $this->plugin('siteSetting');
$currentLocale = $this->siteSetting('locale') ?: 'en_US';
?>

<div class="grix-x grid-container">
    <?php if (!empty($heading)): ?>
        <div class="media-text-heading">
            <h2 class="h2 padding-vertical-1"><?= $heading ?></h2>
        </div>
    <?php endif; ?>
</div>
<div class="col-container col-media-container medium-padding-1">
    <?php foreach ($attachments as $attachment): ?>
        <div class="item-showcase item resource margin-bottom-3 text-center">
            <?php
            $item = $attachment->item();
            if ($item):
                ?>
                <?php
            $media = $attachment->media() ? : $item->primaryMedia();
            $mediaRenderer = $media->renderer();
            if ($media) : ?>
                <div class="responsive-embed aspect16_9 radius">
                <?php echo $media->render([
                    'thumbnailType' => $thumbnailType,
                ]); ?>
                </div>
            <?php endif;
            ?>
                    <?php $showTitleOption = $this->showTitleOption; ?>
                    <?php if ($showTitleOption == 'item_title'): ?>
                        <div class="separator-center metadata">
                            <h2 class="margin-top-1"><?php echo $item->displayTitle(); ?></h2>
                        </div>
                    <?php elseif ($showTitleOption == 'file_name'): ?>
                        <div class="separator-center metadata">
                            <h2 class="margin-top-1"><?php echo $media->displayTitle(); ?></h2>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
                <div class="margin-top-1 medium-margin-top-2">
                    <?php
                    $caption = $attachment->caption();             
                    if ($caption):
                        ?>
                        <div class="caption grid-container margin-bottom-1 medium-margin-bottom-2"><?php echo $caption; ?></div>
                    <?php endif; ?>
            <div class="learn-more">
                <?php if ($currentLocale == 'es'): ?>
                    <p class="button medium warning hollow"><?php echo $item->link("Ver más"); ?></h2>
                <?php else: ?>
                    <p class="button medium warning hollow"><?php echo $item->link("View full item"); ?></h2>
                <?php endif; ?>
            </div>
                </div>
        </div>
    <?php endforeach; ?>
</div>
