<div class="grix-x grid-container">
    <?php if (!empty($heading)): ?>
        <div class="media-text-heading">
            <h3 class="h2 padding-vertical-1"><?= $heading ?></h3>
        </div>
    <?php endif; ?>
</div>
<div class="col-container col-media-container medium-padding-1" data-target-region-id="<?php echo $this->targetID; ?>">
    <?php foreach ($attachments as $attachment): ?>
        <div class="item-showcase max-image-height item resource small-margin-bottom-1 medium-margin-bottom-2 text-center">
            <?php
            $item = $attachment->item();
            if ($item):
                ?>
                <?php
                $title = $this->plugin('escapeHtml')($item->displayTitle());
                $media = $attachment->media() ?: $item->primaryMedia();
                if ($media):
                    $image = preg_match('/alt=""/', $this->thumbnail($media, $this->thumbnailType)) == 1 ? $this->thumbnail($media, $this->thumbnailType, ['alt' => $title]) : $this->thumbnail($media, $this->thumbnailType);
                    echo $image;
                endif;                
                ?>
                    <?php $showTitleOption = $this->showTitleOption; ?>
                    <?php if ($showTitleOption == 'item_title'): ?>
                        <div class="separator-center metadata">
                            <h3 class="margin-top-1"><?php echo $item->link($item->displayTitle()); ?></h3>
                        </div>
                    <?php elseif ($showTitleOption == 'file_name'): ?>
                        <div class="separator-center metadata">
                            <h3 class="margin-top-1"><?php echo $media->displayTitle(); ?></h3>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            <?php
            $caption = $attachment->caption();
            if ($caption):
                ?>
                <div class="caption padding-1 grid-container text-left"><?php echo $caption; ?></div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>