<?php
$siteSetting = $this->plugin('siteSetting');
$currentLocale = $this->siteSetting('locale') ?: 'en_US';
?>

<div class="grix-x grid-container">
	<?php if (!empty($heading)): ?>
	<div class="media-text-heading">
		<h2 class="h2 padding-vertical-1"><?= $heading ?></h2>
	</div>
	<?php endif; ?>
</div>
<div class="item-showcase grid-x grid-margin-x grid-margin-y flex-dir-column">
	<?php foreach ($attachments as $attachment): ?>
	<div class="class=item resource cell small-12 medium-6">
		<?php
  $item = $attachment->item();
  if ($item): ?>
		<?php
  $media = $attachment->media() ?: $item->primaryMedia();
  if ($media):
      echo $this->thumbnail($media, $this->thumbnailType);
  endif;
  ?>
		<?php $showTitleOption = $this->showTitleOption; ?>
		<?php if ($showTitleOption == "item_title"): ?>
		<h2"><?php echo $item->displayTitle(); ?></h2>
			<?php elseif ($showTitleOption == "file_name"): ?>
			<h2><?php echo $media->displayTitle(); ?></h2>
			<?php endif; ?>
			<?php endif;
  ?>

		<div class="margin-top-1 medium-margin-top-2">
			<?php
			$caption = $attachment->caption();             
			if ($caption):
				?>
				<div class="caption margin-bottom-1 medium-margin-bottom-2"><?php echo $caption; ?></div>
			<?php endif; ?>
			<div class="learn-more">
				<p class="button medium warning hollow"><?php echo $item->link("View full item"); ?></h2>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
</div>