<?php 
$this->headScript()->appendFile($this->assetUrl('js/vue.js'));
$this->headScript()->appendFile($this->assetUrl('js/panel-truck.js'));
?>

<div class="grix-x grid-container">
    <?php if (!empty($heading)): ?>
        <div class="media-text-heading medium-offset-1 large-offset-2">
            <h2 class="h2 padding-vertical-1"><?= $heading ?></h2>
        </div>
    <?php endif; ?>
</div>
<div class="full-width-css medium-padding-horizontal-1 large-padding-horizontal-2 xlarge-padding-horizontal-3">
    <div class="col-container col-media-container medium-padding-1">
        <?php foreach ($attachments as $attachment): ?>
            <div class="item-showcase item-showcase-openseadragon item resource margin-bottom-3 text-center">
                <?php
                $item = $attachment->item();
                if ($item):
                    ?>
                    <?php
                $media = $attachment->media() ? : $item->primaryMedia();
                $mediaRenderer = $media->renderer();
                if ($media) :
                    echo $media->render([
                        'thumbnailType' => $thumbnailType,
                    ]);
                endif;
                ?>
                        <?php $showTitleOption = $this->showTitleOption; ?>
                        <?php if ($showTitleOption == 'item_title'): ?>
                            <div class="separator-center metadata">
                                <h2 class="margin-top-2"><?php echo $item->displayTitle(); ?></h2>
                            </div>
                        <?php elseif ($showTitleOption == 'file_name'): ?>
                            <div class="separator-center metadata">
                                <h2 class="margin-top-2"><?php echo $media->displayTitle(); ?></h2>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                <div class="margin-top-1 medium-margin-top-2">
                    <?php
                    $caption = $attachment->caption();             
                    if ($caption):
                        ?>
                        <div class="caption grid-container margin-bottom-1 medium-margin-bottom-2"><?php echo $caption; ?></div>
                    <?php endif; ?>
                    <div class="learn-more">
                        <h2 class="button medium warning"><?php echo $item->link("View full item"); ?></h2>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
