<div id="block-<?php echo $this->blockId; ?>" class="full-width grid-y grid-margin-y margin-top-1 medium-margin-top-0 small-padding-0 medium-padding-1 large-padding-horizontal-2 region <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?> ">
    <div class="grid-x grid-margin-x flex-container align-spaced">
        <?php foreach ($attachments as $attachment): ?>
            <div class="item-showcase item-listing-item item resource flex-dir-column small-margin-bottom-1 medium-margin-bottom-2">
                <?php
                $item = $attachment->item();
                if ($item):
                    ?>
                    <?php
                    $title = $this->plugin('escapeHtml')($item->displayTitle());
                    $media = $attachment->media() ?: $item->primaryMedia();
                    ?>
                    <div class="separator-center metadata">
                        <?php $showTitleOption = $this->showTitleOption; ?>
                        <?php if ($showTitleOption == 'item_title'): ?>
                            <h2 class="margin-top-1"><?php echo $item->displayTitle(); ?></h2>
                        <?php elseif ($showTitleOption == 'file_name'): ?>
                            <h2 class="margin-top-1"><?php echo $media->displayTitle(); ?></h2>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php
                        $date = $item->value('dcterms:date');
                        if ($date):
                        ?>
                        <h2><small date><?php echo $date; ?></small></h2>
                    <?php endif; ?>
                    <?php
                        $origin = $item->value('curation:location');
                        if ($origin):
                        ?>
                        <h2><small origin><?php echo $origin; ?></small></h2>
                    <?php endif; ?>
                    </div>
                <div class="margin-top-1 medium-margin-top-2">
                    <?php
                    $caption = $attachment->caption();
                    if ($caption):
                        ?>
                        <div class="caption padding-1 grid-container margin-bottom-1 medium-margin-bottom-2"><?php echo $caption; ?></div>
                    <?php endif; ?>
                    <?php
                        $identifier = $item->value("dcterms:identifier");
                        if ($identifier): ?>
                            <p class="h4 margin-bottom-1"><small><?php echo "Ref. " . $identifier; ?></small></p>
                        <?php endif;
                        ?>
                    <div class="learn-more">
                        <h2 class="button large warning"><?php echo $item->link("View full item"); ?></h2>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>