<?php

$assetUrl = $this->plugin('assetUrl');
$this->headLink()->appendStylesheet($assetUrl('css/style.css', 'PageBlocks'));

?>

<section class="col-container col-media-container padding-1 large-padding-vertical-2 xlarge-padding-vertical-3">
    <?php foreach ($attachments as $attachment): ?>
        <?php $item = $attachment->item(); 
            $media = $attachment->media() ? : $item->primaryMedia();
            $mediaRenderer = $media->renderer();
            $mediaType = $media->mediaType();
            ?>
        <div class="col-single">
            <?php if ($media && $mediaRenderer === 'iiif') :
                    echo $item->linkRaw($this->thumbnail($media, 'medium-large'));
                    elseif ($media && $mediaType === 'image/jpeg') :
                    echo $item->linkRaw($this->thumbnail($media, 'medium-large'));
                    elseif ($media) :
                    echo $media->render();
            endif; ?>
        </div>
        <div class="col-single">
            <div class="caption padding-1 xlarge-padding-bottom-3"><?= $html ?></div>
        </div>
    <?php endforeach; ?>
</section>
