<?php

$lang = explode('-', $this->lang())[0];
$assetUrl = $this->plugin('assetUrl');
$this->headLink()->appendStylesheet($assetUrl('css/style.css', 'PageBlocks'));

?>

<section class="col-container col-media-container media-details-container padding-1 large-padding-vertical-2 xlarge-padding-vertical-3">
    <?php foreach ($attachments as $attachment): ?>
        <?php $item = $attachment->item(); 
            $media = $attachment->media() ? : $item->primaryMedia();
            $mediaRenderer = $media->renderer();
            $mediaType = $media->mediaType();
        ?>
        <div class="col-single">
            <?php if ($media && $mediaRenderer === 'iiif') :
                   echo $item->linkRaw($this->thumbnail($media, 'medium-large'));
                   elseif ($media && $mediaType === 'image/jpeg') :
                   echo $item->linkRaw($this->thumbnail($media, 'medium-large'));
                   elseif ($media) :
                   echo $media->render();
            endif; ?>
            <?php if ($showHeading): ?>
                <h3 class="padding-top-1 text-center"><?= $item->link($item->displayTitle('', $lang)) ?></h3>
            <?php endif; ?>
            <?php if (!empty($properties)): ?>
                <?php foreach ($properties as $property): ?>
                    <p class="h5 subheader text-center"><?= $item->value($property, [ 'type' => 'literal', 'lang' => $lang ])
                        ?? $item->value($property, [ 'type' => 'literal' ]) ?></p>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php
            $caption = $attachment->caption();
            if ($caption):
            ?>
                <div class="caption padding-1 xlarge-padding-bottom-3"><?php echo $caption; ?></div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</section>