<section class="full-width-css background-colour-light-gray">  
    <div id="block-<?php echo $this->blockId; ?>" class="blockquote-wrapper">
        <blockquote>
            <h3><?php echo $this->html; ?></h3>
            <?php if (!empty($this->attribution)): ?>
            <cite>
                <p><?php echo $this->attribution; ?></p>
            </cite>
            <?php endif; ?>
        </blockquote>
    </div>
</section>