<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $heading
 * @var string $html
 * @var string $alignmentClass "left" or "right"
 * @var string $thumbnailType
 * @var string $showTitleOption "item_title" or "file_name" or "none".
 * @var string $captionPosition "center", "left" or "right".
 */

$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$siteSetting = $this->plugin('siteSetting');

$linkType = $siteSetting('attachment_link_type', 'item');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
?>

<div class="block media-text full-width-css grid-x grid-padding-x margin-bottom-1 background-colour-uom-footer">
    <?php if (!empty($heading)): ?>
    <div class="media-text-heading margin-bottom-1">
        <h3 class="h2 padding-vertical-1"><?= $escape($heading) ?></h3>
    </div>
    <?php endif; ?>
    <button type="button" class="button" data-toggle="offCanvasPush">View Text</button>
    <div class="cell off-canvas-content">
        <div class="media file medium-12">
        <div class="attachments resource-text-openseadragon">
                <?php
                foreach ($attachments as $attachment):
                    $render = null;
                    $title = null;
                    $link = null;
                    $item = $attachment->item();
                    if ($item):
                        $media = $attachment->media() ? : $item->primaryMedia();
                        $mediaRenderer = $media->renderer();
                        $mediaType = $media->mediaType();
                    echo $media->render([
                    'thumbnailType' => $thumbnailType,
                    'link' => $link,
                        ]);

                        if ($showTitleOption == 'item_title'):
                            $title = $item->displayTitle(null, $lang);
                        elseif ($media && $showTitleOption == 'file_name'):
                            $title = $media->displayTitle(null, $lang);
                        endif;

                        if ($title):
                            if ($media && $linkType === 'media'):
                                $link = $media->link($title);
                            elseif ($media && $linkType === 'original' && $media->hasOriginal()):
                                $link = $hyperlink($title, $media->originalUrl());
                            else:
                                $link = $item->link($title);
                            endif;
                        endif;
                    endif;
                $caption = $attachment->caption();
                ?>
                <div class="item resource">
                    <?= $render ?>
                    <?php if ($attachment->caption()): ?>
                    <div class="caption">
                        <?php echo $caption; ?>
                    </div>
                    <?php endif; ?>
                </div>
                <?php endforeach; ?>
            </div>
    <div class="medium-4">
        <div class="off-canvas-wrapper">
            <div class="off-canvas-absolute position-right" id="offCanvasPush" data-off-canvas-content>
                <div class="resource-text flex-container flex-dir-column align-center padding-1 large-padding-2 xlarge-padding-3 off-canvas-absolute position-left" data-off-canvas data-content-scroll="false">
                    <div class="metadata margin-bottom-1 separator-center">
                        <?php $showTitleOption = $this->showTitleOption; ?>
                        <?php if ($showTitleOption == 'item_title'): ?>
                            <h3><?php echo $item->link($item->displayTitle()); ?></h3>
                            <?php elseif ($showTitleOption == 'file_name'): ?>
                            <h3><?php echo $item->link($media->displayTitle()); ?></h3>
                        <?php endif; ?>
                    </div>
                    <div class="text font-wide">
                        <?= $html ?>
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
    </div>
</div>
