<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $heading
 * @var string $html
 * @var string $alignmentClass "left" or "right"
 * @var string $thumbnailType
 * @var string $showTitleOption "item_title" or "file_name" or "none".
 * @var string $captionPosition "center", "left" or "right".
 */

$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$siteSetting = $this->plugin('siteSetting');

$linkType = $siteSetting('attachment_link_type', 'item');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
?>

<div class="block media-text grid-x grid-padding-x align-spaced">
    <?php if (!empty($heading)): ?>
    <div class="media-text-heading">
        <h3 class="h2 padding-vertical-1"><?= $escape($heading) ?></h3>
    </div>
    <?php endif; ?>
    <div class="large-7">
    <button class="button" id="example-dropdown" type="button" data-toggle="reveal-image">Click to view image</button>
        <div class="flex-container align-spaced large-padding-right-1 large-padding-right-0 large-padding-top-1">  
            <div class="attachments dropdown-pane" id="reveal-image" data-dropdown data-auto-focus="true">
                <div class="<?= $alignmentClass . ' ' . $thumbnailType . ' captions-' . $captionPosition ?> media file media-text-image">
                
                    <?php
                        foreach ($attachments as $attachment):
                            $render = null;
                            $title = null;
                            $link = null;
                            $item = $attachment->item();
                            if ($item):
                                $media = $attachment->media() ? : $item->primaryMedia();
                                $mediaRenderer = $media->renderer();
                                $mediaType = $media->mediaType();
                                if ($media && $mediaRenderer === 'iiif') :
                            echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                            elseif ($media && $mediaType === 'image/jpeg') :
                            echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                            elseif ($media) :
                            echo $media->render([
                            'thumbnailType' => $thumbnailType,
                            'link' => $link,
                                ]);
                            endif;

                                if ($showTitleOption == 'item_title'):
                                    $title = $item->displayTitle(null, $lang);
                                elseif ($media && $showTitleOption == 'file_name'):
                                    $title = $media->displayTitle(null, $lang);
                                endif;

                                if ($title):
                                    if ($media && $linkType === 'media'):
                                        $link = $media->link($title);
                                    elseif ($media && $linkType === 'original' && $media->hasOriginal()):
                                        $link = $hyperlink($title, $media->originalUrl());
                                    else:
                                        $link = $item->link($title);
                                    endif;
                                endif;
                            endif;

                            $caption = $attachment->caption();
                        ?>
                        <div class="item resource">
                            <?= $render ?>                
                            <div class="caption">
                            <?= $caption ?>                   
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
            </div>
        </div>
    </div>
    <div class="resource-text large-5 flex-container flex-dir-column align-center padding-1 large-padding-2 xlarge-padding-3">
    <div class="metadata margin-bottom-1 separator-center">
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <h3 class="h2"><?php echo $item->link($item->displayTitle()); ?></h3>
        <?php elseif ($showTitleOption == 'file_name'): ?>
        <h3 class="h2"><?php echo $item->link($media->displayTitle()); ?></h3>
        <?php endif; ?>
      </div>
    <div class="text font-wide">
        <?= $html ?>
    </div>
</div>
</div>