<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $heading
 * @var string $html
 * @var string $alignmentClass "left" or "right"
 * @var string $thumbnailType
 * @var string $showTitleOption "item_title" or "file_name" or "none".
 * @var string $captionPosition "center", "left" or "right".
 */

$escape = $this->plugin("escapeHtml");
$hyperlink = $this->plugin("hyperlink");
$siteSetting = $this->plugin("siteSetting");

$linkType = $siteSetting("attachment_link_type", "item");

$filterLocale = (bool) $this->siteSetting("filter_locale_values");
$lang = $filterLocale ? $this->lang() : null;
?>
<div class="block media-text full-width-css grid-x grid-padding-x padding-1 large-padding-2 margin-bottom-1">
   <?php if (!empty($heading)): ?>
   <div class="media-text-heading medium-offset-1 large-offset-2 margin-bottom-1">
      <h2 class="h2 padding-vertical-1"><?= $escape($heading) ?></h2>
   </div>
   <?php endif; ?>
   <div class="<?= $alignmentClass .
       " " .
       $thumbnailType .
       " captions-" .
       $captionPosition ?> media file large-7 xlarge-8 padding-horizontal-1 large-padding-horizontal-2 xlarge-padding-horizontal-3">
      <div class="attachments resource-text-openseadragon">
         <?php foreach ($attachments as $attachment):

             $render = null;
             $title = null;
             $link = null;
             $item = $attachment->item();
             if ($item):
                $media = $attachment->media() ? : $item->primaryMedia();
                $mediaRenderer = $media->renderer();
                $mediaType = $media->mediaType();
               echo $media->render([
               'thumbnailType' => $thumbnailType,
               'link' => $link,
                ]);

                if ($showTitleOption == 'item_title'):
                    $title = $item->displayTitle(null, $lang);
                elseif ($media && $showTitleOption == 'file_name'):
                    $title = $media->displayTitle(null, $lang);
                endif;

                if ($title):
                    if ($media && $linkType === 'media'):
                        $link = $media->link($title);
                    elseif ($media && $linkType === 'original' && $media->hasOriginal()):
                        $link = $hyperlink($title, $media->originalUrl());
                    else:
                        $link = $item->link($title);
                    endif;
                endif;
            endif;

             $caption = $attachment->caption();
             ?>
            <?= $render ?>
            <div class="caption margin-horizontal-1 padding-1">
                <?= $caption ?>                   
            </div>
         <?php
         endforeach; ?>
      </div>
   </div>
   <div class="resource-text large-5 xlarge-4 flex-container flex-dir-column align-start align-middle padding-1 large-padding-2">
        <div class="metadata margin-bottom-1 separator-center">
            <?php $showTitleOption = $this->showTitleOption; ?>
            <?php if ($showTitleOption == "item_title"): ?>
            <h2><?php echo $item->displayTitle(); ?></h2>
            <?php elseif ($showTitleOption == "file_name"): ?>
            <h2><?php echo $media->displayTitle(); ?></h2>
            <?php endif; ?>
            <?php
            $date = $item->value("dcterms:date");
            if ($date): ?>
            <h2><small date><?php echo $date; ?></small></h2>
            <?php endif;
            ?>
            <?php
            $origin = $item->value("curation:location");
            if ($origin): ?>
            <h2><small origin><?php echo $origin; ?></small></h2>
            <?php endif;
            ?>
        </div>
        <div class="text">
            <?= $html ?>
            <?php
            $identifier = $item->value("dcterms:identifier");
            if ($identifier): ?>
            <h2 class="h4"><small><?php echo "Ref. " . $identifier; ?></small></h2>
            <?php endif;
            ?>
        </div>
        <div class="learn-more">
            <h2 class="button large warning"><?php echo $item->link("View full item"); ?></h2>
        </div>
    </div>
</div>
