<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $heading
 * @var string $html
 * @var string $alignmentClass "left" or "right"
 * @var string $thumbnailType
 * @var string $showTitleOption "item_title" or "file_name" or "none".
 * @var string $captionPosition "center", "left" or "right".
 */

$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$siteSetting = $this->plugin('siteSetting');

$linkType = $siteSetting('attachment_link_type', 'item');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
?>

<div class="block media-text grid-x grid-padding-x full-width align-center padding-1">
    <?php if (!empty($heading)): ?>
    <div class="grid-container cell margin-bottom-1">
    <h3><?= $escape($heading) ?></h3>
    </div>
    <?php endif; ?>

    <div class="cell <?= $alignmentClass . ' ' . $thumbnailType . ' captions-' . $captionPosition ?> media file large-7">
        <div class="attachments">
        <?php
            foreach ($attachments as $attachment):
                $render = null;
                $title = null;
                $link = null;
                $item = $attachment->item();
                if ($item):
                    $media = $attachment->media() ? : $item->primaryMedia();
                    $mediaRenderer = $media->renderer();
                    $mediaType = $media->mediaType();
                    if ($media && $mediaRenderer === 'iiif') :
                   echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                   elseif ($media && $mediaType === 'image/jpeg') :
                   echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                   elseif ($media) :
                   echo $media->render([
                   'thumbnailType' => $thumbnailType,
                   'link' => $link,
                    ]);
                endif;

                    if ($showTitleOption == 'item_title'):
                        $title = $item->displayTitle(null, $lang);
                    elseif ($media && $showTitleOption == 'file_name'):
                        $title = $media->displayTitle(null, $lang);
                    endif;

                    if ($title):
                        if ($media && $linkType === 'media'):
                            $link = $media->link($title);
                        elseif ($media && $linkType === 'original' && $media->hasOriginal()):
                            $link = $hyperlink($title, $media->originalUrl());
                        else:
                            $link = $item->link($title);
                        endif;
                    endif;
                endif;

                $caption = $attachment->caption();
            ?>
            <div class="item resource">
                <?= $render ?>
                <?= $link ?>
                <div class="caption">
                    <?= $caption ?>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="text large-5 flex-container align-middle font-wide padding-1">
        <?= $html ?>
    </div>
</div>