<div id="block-<?php echo $this->blockId; ?>" class="full-width-css grid-x grid-padding-x margin-bottom-1 flex-container section-intro-splash region <?php echo $this->regionClass; ?>  <?php echo $titleSlideTextAlignment ?>" data-target-region-id="<?php echo $this->targetID; ?> ">
    <div class="items">
        <?php foreach ($attachments as $attachment): ?>
            <?php
                $item = $attachment->item();
            ?>
            <div class="large-7 item resource item-listing-image item resource">
                <?php if ($item):
                    $title = $this->plugin('escapeHtml')($item->displayTitle());
                    $media = $attachment->media() ?: $item->primaryMedia();
                    if ($media):
                        $image = preg_match('/alt=""/', $this->thumbnail($media, $this->thumbnailType)) == 1 ? $item->linkRaw($this->thumbnail($media, $this->thumbnailType, ['alt' => $title])) : $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
                ?>
                      <figure>
                          <?php echo $image; ?>
                          <?php if ($attachment->caption()): ?>
                            <figcaption><?php echo $attachment->caption(); ?></figcaption>
                          <?php endif; ?>
                      </figure>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="<div class='large-5 grid-y grid-padding-y padding-2 title-area background-colour-uom-footer flex-container align-spaced item resource introduction">
        <div class='introductory-text'>
            <?php if (!empty($titleSlideTitle)): ?>
                <h1><?php echo $titleSlideTitle; ?></h1>
            <?php endif; ?>
            <?php if (!empty($titleSlideIntro)): ?>
                <?php echo $titleSlideIntro; ?>
            <?php endif; ?>
        </div>
    </div>
</div>


