<div id="block-<?php echo $this->blockId; ?>" class="site-promo grid-x grid-padding-x flex-child-grow small-padding-vertical-1 large-padding-vertical-2 region <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <?php foreach ($attachments as $attachment): ?>
        <?php
            $item = $attachment->item();
        ?>
        <div class="site-image large-6">
            <?php if ($item):
                $title = $this->plugin('escapeHtml')($item->displayTitle());
                $media = $attachment->media() ?: $item->primaryMedia();
                if ($media):
                $image = preg_match('/alt=""/', $this->thumbnail($media, 'large')) == 1 ? $this->thumbnail($media, 'large', ['alt' => $title]) : $this->thumbnail($media, 'large');
            ?>
                    <figure>
                        <?php echo $image; ?>
                        <?php if ($attachment->caption()): ?>
                        <figcaption class="orbit-caption caption"><?php echo $attachment->caption(); ?></figcaption>
                        <?php endif; ?>
                    </figure>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
    <div class="site-promo-text large-6 flex-container flex-dir-column padding-1 medium-padding-2">
        <h2><a href="<?php echo $this->baseUrl . $this->siteSelectLink; ?>"><?php echo $this->siteSelectTitle; ?></a></h2>
        <?php if($this->containsHarmfulContent == 1): ?>
            <div class="site-promo-harmful-content-flag">
                <h2>May contain harmful content</h2>
            </div>
        <?php endif; ?>
        <p><?php echo $this->html; ?></p>
    </div>
</div>