<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *
 * The optional class, url and label may be set at start of caption like:
 * ```
 * url = https://example.org/
 * class = xxx yyy
 * label = Any zzz
 * Next lines are the true caption, that may be raw text ot html.
 * ```
 *
 * The string may be html.
 * The url may be a local media file, for example `/files/original/xxx.pdf`.
 * The label is used when there is no page, so no alt_link_title.
 *
 * @see \BlockPlus\View\Helper\AssetElement
 * @uses \BlockPlus\View\Helper\CaptionClassAndUrl
 */

// Note: this hero uses the classes and js of Twitter Bootstrap.
// The hero uses a random asset.

if (!count($attachments)) return;

$attachment = $attachments[array_rand($attachments)];
if (empty($attachment['asset'])) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// Manage minimal display when the module is disabled.
$captionClassAndUrl = $plugins->has('captionClassAndUrl')
    ? $plugins->get('captionClassAndUrl')
    : fn($string) => [trim((string) $string), '', '', '', false, false, $string !== strip_tags($string)];

$asset = $attachment['asset'];
$page = $attachment['page'] ?? null;
[$caption, $class, $url, $label, $isLocalUrl, $isMediaFile, $isHtmlCaption] = $captionClassAndUrl($attachment['caption'] ?? '');
$title = strlen($attachment['alt_link_title'])
    ? $attachment['alt_link_title']
    : ($page ? $page->title() : $label);
?>

<div class="full-width grid-x grid-padding-x asset-hero-horizontal">
    <div class="small-12 large-7 xlarge-8 asset-hero-horizontal-img block header-wrapper<?= strlen($class) ? ' ' . $escapeAttr($class) : '' ?>" style="background-image:url(<?= $asset->assetUrl() ?>);">
    </div>

    <div class="small-12 large-5 xlarge-4 asset-title-caption padding-1 large-padding-horizontal-2 flex-container align-center align-middle flex-dir-column">
            <!-- Display the title as an H1 if $title has content -->
            <?php if (strlen(trim($title))): ?>
                <div class="flex-container align-left">
                    <div class="flex-container align-left">
                        <div class="flex-container align-middle margin-bottom-1">
                            <h1><?= $escape($title) ?></h1>
                        </div>
                    </div>
                <?php endif; ?>
            </div>

        <?php if (strlen($caption)): ?>
            <p><?= $isHtmlCaption ? $caption : $escape($caption) ?></p>
        <?php endif; ?>
    </div>
</div>