<?php $escape = $this->plugin('escapeHtml'); ?>

<div class="assets">
    <?php foreach ($attachments as $attachment): ?>
        <?php 
        $asset = $attachment['asset']; 
        $assetImage = ($asset) ? $this->thumbnail($asset, 'square', ['class' => 'thumbnail']) : ''; 
        $altLinkTitle = $attachment['alt_link_title'] ?? null; 
        $caption = $attachment['caption'] ?? null; 
        $page = $attachment['page'] ?? null;
        ?>

        <div class="asset media-object medium-padding-1 <?php echo ($assetImage !== '') ? 'has-image' : ''; ?>">

            <?php if ($page): ?>
                <a href="<?php echo $escape($page->siteUrl()); ?>">
                    <?php echo $assetImage; ?>
                    <?php if ($altLinkTitle || $caption): ?>
                        <div class="media-object-title-caption medium-padding-1 large-padding-1">
                            <?php if ($altLinkTitle): ?>
                                <div class="alt-link-title">
                                    <span class="link-title h4 margin-bottom-1"><?php echo $escape($altLinkTitle); ?></span>
                                </div>
                            <?php endif; ?>
                            <?php if ($caption): ?>
                                <div class="caption"><?php echo $escape($caption); ?></div>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </a>
            <?php elseif ($altLinkTitle): ?>
                <a href="<?php echo $altLinkTitle; ?>" class="flex-container flex-dir-column medium-flex-dir-row align-center align-middle">
                    <div class="media-object-section medium-padding-right-1 flex-container">
                        <?php echo $assetImage; ?>
                    </div>
                    <div class="media-object-section padding-1 flex-container">
                        <?php if ($caption): ?>
                            <div class="media-object-title-caption">
                                <div class="caption"><?php echo $escape($caption); ?></div>
                            </div>
                        <?php endif; ?>
                    </div>
                </a>
            <?php else: ?>
                <?php echo $assetImage; ?>
                <?php if ($altLinkTitle || $caption): ?>
                    <div class="media-object-title-caption medium-padding-1">
                        <?php if ($altLinkTitle): ?>
                            <div class="alt-link-title">
                                <span class="link-title h4 margin-bottom-1"><?php echo $escape($altLinkTitle); ?></span>
                            </div>
                        <?php endif; ?>
                        <?php if ($caption): ?>
                            <div class="caption"><?php echo $escape($caption); ?></div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
