<?php $escape = $this->plugin('escapeHtml'); ?>

<div class="assets">
  <?php foreach ($attachments as $attachment): ?>
    <?php $asset = $attachment['asset']; ?>
    <?php $assetImage = ($asset) ? $this->thumbnail($asset, 'square', ['class' => 'thumbnail']) : ''; ?>
    <div class="asset media-object <?php echo ($assetImage !== '') ? 'has-image' : ''; ?>">
        <?php $page = (array_key_exists('page', $attachment)) ? $attachment['page'] : null; ?>
        <div class="media-object-section">
        <?php if ($page): ?>
            <a href="<?php echo $escape($page->siteUrl()); ?>">
                <?php $altLinkTitle = ($attachment['alt_link_title'] !== '') ? $escape($attachment['alt_link_title']) : false; ?>
                <?php echo $assetImage; ?>
            </a>
                <span class="link-title"><?php echo ($altLinkTitle) ? $altLinkTitle : $escape($page->title()); ?></span>
            <?php if ($attachment['caption'] !== ''): ?>
                <div class="caption"><?php echo $escape($attachment['caption']); ?></div>
            <?php endif; ?>
            <?php else: ?>
                <?php echo $assetImage; ?>
                <?php if (!empty($attachment['alt_link_title']) || $attachment['caption'] !== ''): ?>
                    <div class="media-object-title-caption">
                        <?php if (!empty($attachment['alt_link_title'])): ?>
                            <div class="alt-link-title">
                                <span class="link-title h4 margin-bottom-1"><?php echo $escape($attachment['alt_link_title']); ?></span>
                            </div>
                        <?php endif; ?>
                        <?php if ($attachment['caption'] !== ''): ?>
                            <div class="caption"><?php echo $escape($attachment['caption']); ?></div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
  <?php endforeach; ?>
</div>
