<?php $escape = $this->plugin('escapeHtml'); ?>

<?php
// Count the number of attachments that have an 'asset'
$assetCount = count(array_filter($attachments, function($attachment) {
    return !empty($attachment['asset']);
}));

// Assign asset column class based on asset count
$assetColumn = in_array($assetCount, [1, 2, 4]) ? 'asset-column-2' : 'asset-column-3';
?>

<div class="assets <?php echo $assetColumn; ?>">
  <?php foreach ($attachments as $attachment): ?>
    <?php $asset = $attachment['asset']; ?>
    <div class="asset">
        <?php $assetImage = ($asset) ? $this->thumbnail($asset, 'square') : ''; ?>
        <?php $page = (array_key_exists('page', $attachment)) ? $attachment['page'] : null; ?>
        <?php
            echo $assetImage; 
        ?>
        <?php if ($attachment['caption'] !== ''): ?>
        <div class="caption asset-caption"><?php echo $escape($attachment['caption']); ?></div>
        <?php endif; ?>
    </div>
  <?php endforeach; ?>
</div>