<?php $escape = $this->plugin('escapeHtml'); ?>

<div class="assets text-around-image">
  <?php foreach ($attachments as $attachment): ?>
    <?php $asset = $attachment['asset']; ?>
    <div class="asset">
        <?php $assetImage = ($asset) ? $this->thumbnail($asset, 'square') : ''; ?>
        <?php $page = (array_key_exists('page', $attachment)) ? $attachment['page'] : null; ?>
        <?php
            echo $assetImage; 
        ?>
        <?php if ($attachment['caption'] !== ''): ?>
        <div class="caption asset-caption"><?php echo $escape($attachment['caption']); ?></div>
        <?php endif; ?>
    </div>
  <?php endforeach; ?>
</div>