<?php

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $assets Deprecated, alias of attachments.
 * @var string $heading
 * @var string $className
 * @var string $alignment
 */

// Note: this hero uses the classes and js of Twitter Bootstrap.
// The hero uses a random asset.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
[$caption, $class, $url, $label, $isLocalUrl, $isMediaFile, $isHtmlCaption] = $this->captionClassAndUrl($attachment['caption']);
?>

<?php if (!count($attachments)) return; ?>
<?php $attachment = $attachments[array_rand($attachments)]; ?>
<?php if (empty($attachment['asset'])) return; ?>

<div class="full-width-css">
    <div role="banner" class="hero-image image-large region-splash flex-container <?= $escapeAttr($attachment['class']) ?>" style="background-image:linear-gradient(rgba(0, 0, 0, 0.0), rgba(0, 0, 0, 0.6)),url(<?= $attachment['asset']->assetUrl() ?>);">
        <?php if (!empty($heading)) : ?>
            <div class="grid-container grid-x flex-grow align-self-bottom">
                <div class="hero-title dark-background">
                    <h1><?= $heading ?></h1>
                    <?php $attachmentUrl = $attachment['page'] ? $attachment['page']->siteUrl() : ($attachment['url'] ?? null); ?>
                    <?php if ($attachment['alt_link_title'] && $attachmentUrl) : ?>
                        <a href="<?= $escapeAttr($attachmentUrl) ?>"><button class="btn knowmore"><?= $escape($attachment['alt_link_title']) ?></button></a>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <?php if ($attachment['caption'] !== ''): ?>
        <div class="hero-title-caption dark-background">
            <div class="grid-container caption padding-horizontal-1">
                <?= empty($attachment['raw']) ? $attachment['caption'] : $escape($attachment['caption']) ?>
            </div>
        </div>
    <?php endif; ?>
</div>
