<?php

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *   Specific to the module version:
 *   - class (string)
 *   - title (string): deprecated alias of "alt_link_title"
 *   - url (string): deprecated, will be removed. Use "page", "caption", alt title, or original asset alt value instead.
 * @var array $assets Deprecated, alias of attachments.
 * @var string $heading
 * @var string $className
 * @var string $alignment
 */

// Note: this hero uses the classes and js of Twitter Bootstrap.
// The hero uses a random asset.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<div role="banner" class="asset-hero full-width-css grid-x region-splash">
    <?php if (!count($attachments)) return; ?>
    <?php $attachment = $attachments[array_rand($attachments)]; ?>
    <?php if (empty($attachment['asset'])) return; ?>
    <div class="small-12 large-7 xlarge-8">
        <div class="hero-image image-xlarge flex-container <?= $escapeAttr($attachment['class']) ?>" style="background-image:linear-gradient(rgba(0, 0, 0, 0.0), rgba(0, 0, 0, 1)),url(<?= $attachment['asset']->assetUrl() ?>);">
        </div>
    </div>

    <div class="small-12 large-5 xlarge-4 flex-container flex-dir-column align-middle align-center colour-scheme-4 text-treatment-2 margin-bottom-0"> 

    <?php if (!empty($heading)) : ?>
        <div class="flex-container"> 
            <h1 class="h1 padding-1 large-padding-horizontal-2 xlarge-padding-horizontal-3"><?= $escape($heading) ?></h1>
        </div>
    <?php endif; ?>

    <?php if ($attachment['caption']) : ?>
        <div class="h4 padding-1 large-padding-horizontal-2 xlarge-padding-horizontal-3"><?= $attachment['caption'] ?></div>
        <?php $attachmentUrl = $attachment['page'] ? $attachment['page']->siteUrl() : ($attachment['url'] ?? null); ?> 
        <?php if ($attachment['alt_link_title'] && $attachmentUrl) : ?>
            <a href="<?= $escapeAttr($attachmentUrl) ?>"><button class="btn knowmore"><?= $escape($attachment['alt_link_title']) ?></button></a>
        <?php endif; ?>
        </div>
    <?php endif; ?>
</div>