<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->headScript()->appendFile($this->assetUrl('js/imagesloaded.pkgd.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/masonry.pkgd.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/browse-masonry.js'));

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$layoutSetting = $this->themeSetting('browse_layout', 'grid');
$bodyTruncate = $this->themeSetting('truncate_body_property');
$gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
$listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
$currentLayout = 'grid';
$isGrid = ($currentLayout == 'grid') ? true : false;
$queryUrl = $this->url(
    'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
);

$showThumbnail = in_array('thumbnail', $this->components);
$showHeading = in_array('resource-heading', $this->components);
$showBody = in_array('resource-body', $this->components);
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');

?>

<div class="preview-block clearfix">
    <?php if ($this->heading) : ?>
        <div class="preview-header">
            <h3><?php echo $this->hyperlink($this->heading, $queryUrl); ?></h3>
        </div>
    <?php endif; ?>
    <div class="resources resource-grid-mosaic">
        <div class="grid-sizer"></div>
        <div class="gutter-sizer"></div>
        <?php
        foreach ($this->resources as $resource):
            $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $resource->displayTitle(null, ($valueLang));
            $body = $bodyTerm ? $resource->value($bodyTerm) : $resource->displayDescription(null, ($valueLang));
            $thumbnail = $this->thumbnail($resource, 'large');
            ?>
            <div class="<?php echo $this->resourceType; ?> resource-masonry grid">
                <!-- Thumbnail -->
                <?php if ($thumbnail && $showThumbnail) : ?>
                    <div class="resource__thumbnail">
                        <?php echo $resource->linkRaw($thumbnail); ?>
                    </div>
                <?php endif; ?>

                <!-- Content -->
                <div class="resource__content h5 text-center">
                    <?php if ($showHeading) : ?>
                        <?php echo $resource->link($heading); ?>
                    <?php endif; ?>

                    <?php if ($showBody && $body) : ?>
                        <div class="description <?php echo ($bodyTruncate) ? $bodyTruncate : ''; ?>"><?php echo $escape($body); ?></div>
                    <?php endif; ?>
                </div>
            </div>

        <?php endforeach; ?>
    </div>

    <?php
    if ($this->linkText) :
        echo $this->hyperlink($this->linkText, $queryUrl, ['class' => 'browse-all button icon-btn']);
    endif;
    ?>

</div>
