<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 */

?>

<div class="reveal-on-scroll lazy-fade-in">  <!-- Load Effect block -->
    <div class="full-width padding-vertical-1">
        <div class="grid-x grid-container">
            <div class="padding-vertical-1 large-padding-vertical-2 lead">
                <?= $block->dataValue('html', '') ?>
            </div>
        </div>
    </div>
</div>