<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 */
$this->headScript()->prependFile($this->assetUrl('js/progress-bar.js'));
?>

<div class="full-width padding-1">
    <div class="grid-x grid-container">
        <div class="text-block padding-vertical-1 large-padding-vertical-2">
            <?= $block->dataValue('html', '') ?>
        </div>
    </div>
</div>