<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 */

?>

<div class="full-width padding-vertical-1 flex-container dark-background">
    <div class="grid-x grid-container flex-container">
        <div class="padding-vertical-1 medium-padding-vertical-2 large-padding-vertical-3">
            <?= $block->dataValue('html', '') ?>
        </div>
    </div>
</div>