<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 */

?>
<div class="reveal-on-scroll lazy-fade-in">  <!-- Load Effect block -->
    <div class="full-width padding-vertical-1 flex-container">
        <div class="grid-x grid-container flex-container blockquote-wrapper">
            <i class="fa fa-quote-left align-middle flex-container margin-right-1 medium-margin-right-2 xlarge-margin-right-3" aria-hidden="true"></i>
            <?php if (!empty($heading)): ?>
                <h2><?= $escape($heading) ?></h2>
            <?php endif; ?>
            <div class="flex-1-1-0 flex-container">
            <?= $block->dataValue('html', '') ?>
            </div>
        </div>
    </div>
</div>