<?php

$assetUrl = $this->plugin('assetUrl');
$this->headLink()->appendStylesheet($assetUrl('css/style.css', 'PageBlocks'));

$image = $this->api()->read('assets', $image)->getContent();

?>

<section class="image-banner grid-x grid-padding-x full-width tint-<?= $tint ?>">
    <?php echo "This is loading" ?>
    <div class="image-container medium-6 large-8">
        <img src="<?= $image->assetUrl() ?>" alt="<?= $image->altText() ?>" />
    </div>
    <div class="overlay-container medium-6 large-4">
        <?php if ($header): ?>
            <h1><?= $header ?></h1>
        <?php endif; ?>
        <?php if ($subheader): ?>
            <p><?= $subheader ?></p>
        <?php endif; ?>
    </div>
</section>