<?php
$this->headLink()->prependStylesheet($this->assetUrl('css/scrollbox-revised.css'));
$this->headScript()->prependFile($this->assetUrl('js/scrollbox.js'));
?>

<?php
$siteSettingService = $this->getHelperPluginManager()->get('siteSetting');
$featuredScrollbox = [];

foreach ($sites as $site):
    $featured = $siteSettingService('extended_site_description_featured', null, $site->id());

    if ($featured):
        $thumbnailUrl = $thumbnails && $site->thumbnail() ? $site->thumbnail()->assetUrl() : null;
        $summary = $summaries ? $site->summary() : null;

        $featuredScrollbox[] = [
            'title' => $site->title(),
            'url' => $site->siteUrl(),
            'featured' => $featured,
            'thumbnail' => $thumbnailUrl,
            'summary' => $summary
        ];
    endif;
endforeach;
?>

<script>
    const featuredScrollbox = <?php echo json_encode($featuredScrollbox); ?>;

    for (const item of featuredScrollbox) {
        const li = $(`
            <li>
                <a class="inner" href="${item.url}">

                <section class="inner2">
                    <img src="${item.thumbnail}" alt="${item.title}">
                    <div>
                        <h4>${item.title}</h4>
                        <p>${item.summary ? item.summary.replace(/\n/g, '<br>') : ''}</p>
                    </div>
			    </section>

                </a>
            </li>
        `);

        
    }
</script>
