<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/scrollbox-revised.css'));
?>

<?php
$siteSettingService = $this->getHelperPluginManager()->get('siteSetting');
$NEW = [];

foreach ($sites as $site):
    $featured = $siteSettingService('extended_site_description_featured', null, $site->id());

    if ($featured):
        $thumbnailUrl = $thumbnails && $site->thumbnail() ? $site->thumbnail()->assetUrl() : null;
        $summary = $summaries ? $site->summary() : null;

        $NEW[] = [
            'title' => $site->title(),
            'url' => $site->siteUrl(),
            'featured' => $featured,
            'thumbnail' => $thumbnailUrl,
            'summary' => $summary
        ];
    endif;
endforeach;
?>

<pre>
<?php print_r($NEW); ?>
</pre>

<script>
    window.NEW = <?php echo json_encode($NEW, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?>;
    </script>

<script src="http://localhost/omeka-s/themes/foundation-s/asset/js/scrollbox-revised.js"></script>

<section class="scrollbox-thrower" style="margin-top: 60px;">
    <aside class="coverleft">&nbsp;</aside>

    <aside class="covermain">
        <h1>Featured stories</h1>
        <section id="featured" class="full-width">
        <ul class="thrower"></ul>
            <nav><button class="throwleft" disabled="disabled">&lt;</button><button class="throwright">&gt;</button></nav>
        </section>
        <a class="viewall" href="./">View all</a>
    </aside>

    <aside class="coverright">&nbsp;</aside>
</section>



