<?php

$hyperlink = $this->plugin('hyperlink');
$thumbnailType = $block->dataValue('thumbnail_type');
?>
<div class="reveal-on-scroll lazy-fade-in">  <!-- Lazy load block -->
    <div class="file-caption-block media-caption-text resourceTextGrid padding-1 large-padding-2">
        <div class="file file-caption-text media-embed xlarge-padding-horizontal-1 <?php echo $this->escapeHtml(implode(' ', $classes)); ?>">
            <?php foreach($attachments as $attachment): ?>
            <?php $item = $attachment->item(); ?>
            <div class="item resource <?php echo $thumbnailType; ?>">
                <?php
                $media = $attachment->media() ?: $item->primaryMedia();
                $mediaRenderer = $media->renderer();
                if ($media):
                    if ($mediaDisplay === 'thumbnail') {
                        switch ($link) {
                            case 'original':
                                $url = $media->originalUrl();
                                break;
                            case 'item':
                                $url = $item->url();
                                break;
                            case 'media':
                                $url = $media->url();
                                break;
                            default:
                                throw new \InvalidArgumentException(sprintf('Invalid link type "%s"', $link));
                        }
                        echo $hyperlink->raw($this->thumbnail($media, $thumbnailType), $url);
                    } else {
                        echo $media->render([
                            'thumbnailType' => $thumbnailType,
                            'link' => $link,
                        ]);
                    }
                endif;
                ?>
                </div>
            </div>
            <!-- Metadata / text -->
            <div class="block-html medium-padding-horizontal-1 xlarge-padding-horizontal-3">

                <?php if ($showTitleOption === 'item_title'): ?>

                    <div class="separator-center metadata margin-vertical-1">

                        <h2 class="item-title">
                            <?php echo $this->escapeHtml($item->displayTitle()); ?>
                        </h2>

                        <?php if ($alternative = $item->value('dcterms:alternative')): ?>
                            <div class="metadata-value italic-font alternative">          
                                <?php echo $this->escapeHtml($alternative); ?>        
                            </div>
                        <?php endif; ?>

                        <?php if ($date = $item->value('dcterms:date')): ?>
                            <div class="metadata-value date">  
                                <?php echo $this->escapeHtml($date); ?>            
                            </div>
                        <?php endif; ?>

                        <?php if ($location = $item->value('curation:location')): ?>
                            <div class="metadata-value location text-center">
                                
                                    <?php echo $this->escapeHtml($location); ?>
                                
                            </div>
                        <?php endif; ?>

                    </div>

                <?php elseif ($showTitleOption === 'file_name'): ?>

                    <div class="separator-center metadata margin-vertical-1">

                        <h2 class="item-title">
                            <?php if ($media): ?>
                                <?php echo $this->escapeHtml($media->displayTitle()); ?>
                            <?php else: ?>
                                <?php echo $this->escapeHtml($item->displayTitle()); ?>
                            <?php endif; ?>
                        </h2>

                        <?php if ($alternative = $item->value('dcterms:alternative')): ?>
                            <div class="metadata-value italic-font alternative">
                                
                                    <?php echo $this->escapeHtml($alternative); ?>
                                
                            </div>
                        <?php endif; ?>

                        <?php if ($date = $item->value('dcterms:date')): ?>
                            <div class="metadata-value date">
                                
                                    <?php echo $this->escapeHtml($date); ?>
                                
                            </div>
                        <?php endif; ?>

                        <?php if ($location = $item->value('curation:location')): ?>
                            <div class="metadata-value location text-center">   
                                <?php echo $this->escapeHtml($location); ?>   
                            </div>
                        <?php endif; ?>

                    </div>

                <?php endif; ?>

                <?php if ($caption = $attachment->caption()): ?>
                    <div class="caption margin-top-1 large-margin-top-2">
                        <?php echo $caption; ?>
                    </div>
                <?php endif; ?>

                <?php
                $identifiers = $item->value(
                    'dcterms:identifier',
                    ['all' => true]
                );
                ?>

                <?php if ($identifiers): ?>
                    <?php foreach ($identifiers as $identifier): ?>
                        <div class="identifier metadata-value">                      
                            <?php echo $this->escapeHtml($identifier); ?>                     
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>

                <div class="learn-more flex-container align-center margin-top-1">
                    <?php
                    echo $item->link(
                        $this->translate('More item information'),
                        null,
                        [
                            'class' =>
                                'button medium warning hollow',
                        ]
                    );
                    ?>
                </div>

            </div><!-- /.block-html -->
            <?php endforeach; ?>
        </div>
        </div>
    <div>
</div>