<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $thumbnailType
 * @var string $showTitleOption "item_title" or "file_name" or "none".
 */

$this->headLink()->appendStylesheet($this->assetUrl('css/annona.css'));
$this->headScript()->appendFile($this->assetUrl('js/annona.js'));

$plugins = $this->getHelperPluginManager();
$hyperlink = $plugins->get('hyperlink');
$siteSetting = $plugins->get('siteSetting');

$linkType = $siteSetting('attachment_link_type', 'item');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
?>

<div class="block media-text">
    <div class="<?= htmlspecialchars($thumbnailType) ?> media file medium-padding-horizontal-1 large-padding-horizontal-2 xlarge-padding-horizontal-3">
        <div class="attachments resource-text-openseadragon">
            <?php foreach ($attachments as $attachment): 
                $render = null;
                $title = null;
                $link = null;
                $item = $attachment->item();
                $caption = $attachment->caption();
                if ($item) {
                    $media = $attachment->media() ?: $item->primaryMedia();
                    if ($media) {
                        echo $media->render([
                            'thumbnailType' => $thumbnailType,
                            'link' => $linkType,
                        ]);
                        if ($showTitleOption == 'item_title') {
                            $title = $item->displayTitle(null, $lang);
                        } elseif ($showTitleOption == 'file_name') {
                            $title = $media->displayTitle(null, $lang);
                        }
                    }
                }
                ?>
                <div class="item resource">
                    <?= $caption ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>