<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $thumbnailType
 * @var string $showTitleOption "item_title" or "file_name" or "none".
 */

$this->headLink()->appendStylesheet($this->assetUrl('css/annona.css'));
$this->headScript()->appendFile($this->assetUrl('js/annona.js'));

$plugins = $this->getHelperPluginManager();
$hyperlink = $plugins->get('hyperlink');
$siteSetting = $plugins->get('siteSetting');

$linkType = $siteSetting('attachment_link_type', 'item');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
?>

<div class="block media-text">
    <div class="<?= htmlspecialchars($thumbnailType) ?> media file medium-padding-horizontal-1 large-padding-horizontal-2 xlarge-padding-horizontal-3">
        <div class="attachments resource-text-openseadragon">
        <?php foreach ($attachments as $attachment): 
            $title = null;
            $link = null;
            $item = $attachment->item();
            $caption = $attachment->caption();
            
            if ($item) {
                $media = $attachment->media() ?: $item->primaryMedia();

                if ($media) {
                    // Render the media with specified options
                    echo $media->render([
                        'thumbnailType' => $thumbnailType,
                        'link' => $linkType,
                    ]);

                    // Determine the title based on the $showTitleOption setting
                    if ($showTitleOption === 'item_title') {
                        $title = $item->displayTitle(null, $lang);
                        $alternative = $item->value('dcterms:alternative');
                        
                        if ($alternative) {
                            echo '<h2 class="h3 italic-font"><small>' . htmlspecialchars($alternative, ENT_QUOTES, 'UTF-8') . '</small></h2>';
                        }
                    } elseif ($showTitleOption === 'file_name') {
                        $title = $media->displayTitle(null, $lang);
                    }
                }
            }
            ?>

            <div class="item resource">
                <?php if ($title): ?>
                    <h3><?= htmlspecialchars($title, ENT_QUOTES, 'UTF-8') ?></h3>
                <?php endif; ?>
                <?= htmlspecialchars($caption, ENT_QUOTES, 'UTF-8') ?>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
</div>