<?php

$hyperlink = $this->plugin('hyperlink');
$thumbnailType = $block->dataValue('thumbnail_type');
$uniqueId = uniqid();
?>

<div class="reveal-on-scroll lazy-fade-in"> <!-- Lazy load block -->
  <div class="full-width file-caption-block media-caption-text resourceTextGrid padding-1 large-padding-2 margin-vertical-1 large-margin-vertical-2">
    <div class="file file-caption-text media-embed xlarge-padding-horizontal-1 <?php echo $this->escapeHtml(implode(' ', $classes)); ?>">
      
      <?php foreach ($attachments as $attachment): ?>
        <?php $item = $attachment->item(); ?>
        
        <div class="item resource <?php echo $thumbnailType; ?>">
            <div class="sensitive-wrapper flex-container align-center align-middle">
                <!-- Toggle button overlay -->
                <button class="sensitive-overlay items-center justify-center text-center" type="button" data-toggle="sensitive-<?php echo $uniqueId; ?>"> 
                    <i class="far fa-eye-slash fa-lg margin-bottom-1 large-margin-bottom-2"></i> 
                    <p class="warning-text"> This item contains content which people may find offensive.<br> Click or press to view. </h2> 
                </button> 
                <!-- Media block with blur applied --> 
                 <div id="sensitive-<?php echo $uniqueId; ?>" class="sensitive-media" data-toggler="sensitive-media-show"> 
                    <?php $media = $attachment->media() ?: $item->primaryMedia(); if ($media): if ($mediaDisplay === 'thumbnail') { switch ($link) { case 'original': $url = $media->originalUrl(); break; case 'item': $url = $item->url(); break; case 'media': $url = $media->url(); break; default: throw new \InvalidArgumentException(sprintf('Invalid link type "%s"', $link)); } echo $hyperlink->raw($this->thumbnail($media, $thumbnailType), $url); } else { echo $media->render([ 'thumbnailType' => $thumbnailType, 'link' => $link, ]); } endif; ?> 
                </div>
            </div>
        </div>
    </div>

    <div class="block-html medium-padding-horizontal-1 xlarge-padding-horizontal-3">
        <?php if ($showTitleOption === 'item_title'): ?>
        <div class="separator-center metadata margin-vertical-1">
            <h2 class="h4"><?php echo $item->displayTitle(); ?></h2>
            <?php if ($alternative = $item->value('dcterms:alternative')): ?>
            <h2 class="h4 italic-font alternative"><small><?php echo $this->escapeHtml($alternative); ?></small></h2>
            <?php endif; ?>
            <?php $date = $item->value("dcterms:date"); ?>
            <?php if ($date): ?>
            <div class="h4 date"><small><?php echo $this->escapeHtml($date); ?></small></div>
            <?php endif; ?>
            <?php if ($location = $item->value('curation:location')): ?>
            <div class="h4 location"><small><?php echo $this->escapeHtml($location); ?></small></div>
            <?php endif; ?>
        </div>
        <?php elseif ($showTitleOption === 'file_name'): ?>
        <div class="separator-center metadata margin-vertical-1">
            <h2 class="h4"><?php echo $media->displayTitle(); ?></h2>
        </div>
        <?php if ($alternative = $item->value('dcterms:alternative')): ?>
            <h2 class="h4 italic-font alternative"><small><?php echo $this->escapeHtml($alternative); ?></small></h2>
        <?php endif; ?>
        <?php $date = $item->value("dcterms:date"); ?>
        <?php if ($date): ?>
            <div class="h4 date"><small><?php echo $this->escapeHtml($date); ?></small></div>
        <?php endif; ?>
        <?php if ($location = $item->value('curation:location')): ?>
            <div class="h4 location"><small><?php echo $this->escapeHtml($location); ?></small></div>
        <?php endif; ?>
        <?php endif; ?>

        <?php $caption = $attachment->caption(); ?>
        <?php if ($caption): ?>
        <div class="caption margin-top-1 large-margin-top-2"><?php echo $caption; ?></div>
        <?php endif; ?>

        <?php
        $identifiers = $item->value('dcterms:identifier', ['all' => true]);
        if ($identifiers):
        foreach ($identifiers as $identifier): ?>
            <h2 class="h4 identifier"><small><?php echo $this->escapeHtml($identifier); ?></small></h2>
        <?php endforeach;
        endif;
        ?>

        <div class="learn-more flex-container align-center">
        <?php echo $item->link("Learn more", null, ['class' => 'button medium warning hollow']); ?>
        </div>
    </div>
    <?php endforeach; ?>
  </div>
</div>