<?php
$hyperlink = $this->plugin('hyperlink');
?>
<div class="full-width resourceTextGrid padding-horizontal-1 large-padding-horizontal-2 xlarge-padding-horizontal-3 margin-vertical-1 large-margin-vertical-2">
    <div class="file file-caption-text media-embed <?php echo $this->escapeHtml(implode(' ', $classes)); ?>">
        <?php foreach($attachments as $attachment): ?>
        <?php $item = $attachment->item(); ?>
        <div class="item resource">
            <?php
            $media = $attachment->media() ?: $item->primaryMedia();
            if ($media):
                if ($mediaDisplay === 'thumbnail') {
                    switch ($link) {
                        case 'original':
                            $url = $media->originalUrl();
                            break;
                        case 'item':
                            $url = $item->url();
                            break;
                        case 'media':
                            $url = $media->url();
                            break;
                        default:
                            throw new \InvalidArgumentException(sprintf('Invalid link type "%s"', $linkType));
                    }
                    echo $this->thumbnail($media, $thumbnailType);
                } else {
                    echo $media->render([
                        'thumbnailType' => $thumbnailType,
                        'link' => $link,
                    ]);
                }
            endif;
            ?>
            </div>
        </div>
        <div class="block-html padding-horizontal-1 large-padding-horizontal-2">
            <?php if ($showTitleOption === 'item_title'): ?>
                <div class="separator-center metadata">
                    <h2 class="margin-vertical-1 large-margin-vertical-2"><?php echo $item->displayTitle(); ?></h2>
                </div>
            <?php elseif ($showTitleOption === 'file_name'): ?>
                <div class="separator-center metadata">
                    <h2><?php echo $media->displayTitle(); ?></h2>
                </div>
            <?php endif; ?>
            <?php $caption = $attachment->caption(); ?>
            <?php if ($caption): ?>
                <div class="caption margin-top-1 large-margin-top-2"><?php echo $caption; ?></div>
            <?php endif; ?>
            <div class="learn-more">
                <button class="button medium warning"><?php echo $item->link("View full item"); ?></button>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
<div>