<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $heading
 * @var string $html
 * @var string $alignmentClass "left" or "right"
 * @var string $thumbnailType
 * @var string $showTitleOption "item_title" or "file_name" or "none".
 * @var string $captionPosition "center", "left" or "right".
 */

$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$siteSetting = $this->plugin('siteSetting');
$uniqueId = uniqid();
$linkType = $siteSetting('attachment_link_type', 'item');
$filterLocale = (bool)$this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null; ?>

<div class="sensitive-material full-width-css block media-text grid-x grid-padding-x align-spaced">
    <?php if (!empty($heading)): ?>
    <div class="media-text-heading medium-offset-1 large-offset-2">
        <h2 class="h2 padding-vertical-1 margin-bottom-1"><?=$escape($heading) ?></h2>
    </div>
    <?php
endif; ?>
    <div class="large-7 flex-container align-center">
        <button id="unblur-image" type="button" data-toggle="blur-image-<?=$uniqueId
?>" class="flex-container flex-dir-column align-spaced align-middle">
            <div class="sensitive-content margin-horizontal-1 padding-horizontal-1 large-padding-horizontal-2 xlarge-padding-horizontal-3 flex-container flex-dir-column">
                <i class="far fa-eye-slash fa-lg"></i>
                <h2 class="h5 warning-text margin-top-1 xlarge-margin-top-2">This item contains sensitive content which people may find offensive. Click or press to view.</h2>
            </div>
            <div class="attachments max-image-height">
                <div class="<?=$alignmentClass . ' ' . $thumbnailType . ' captions-' . $captionPosition ?> media file media-text-image unblur-image" id="blur-image-<?=$uniqueId ?>" data-toggler=".unblur-image">
                    <?php
foreach ($attachments as $attachment):
    $render = null;
    $title = null;
    $link = null;
    $item = $attachment->item();
    if ($item):
        $media = $attachment->media() ? : $item->primaryMedia();
        $mediaRenderer = $media->renderer();
        $mediaType = $media->mediaType();
        if ($media && $mediaRenderer === 'iiif') :
            echo $this->thumbnail($media, $this->thumbnailType);
        elseif ($media && $mediaType === 'image/jpeg') :
            echo $this->thumbnail($media, $this->thumbnailType);
        elseif ($media) :
            echo $media->render(['thumbnailType' => $thumbnailType,'link' => $link,]);
        endif;
    

        if ($showTitleOption == 'item_title'):
            $title = $item->displayTitle(null, $lang);
        elseif ($media && $showTitleOption == 'file_name'):
            $title = $media->displayTitle(null, $lang);
        endif;

        if ($title):
            if ($media && $linkType === 'media'):
                $link = $media->link($title);
            elseif ($media && $linkType === 'original' && $media->hasOriginal()):
                $link = $hyperlink($title, $media->originalUrl());
            else:
                $link = $item->link($title);
            endif;
        endif;
    endif;
    $caption = $attachment->caption(); ?>
                    <div class="item resource">
                        <?=$render
?>
                        <div class="caption margin-horizontal-1 padding-1">
                            <?=$caption
?>
                        </div>
                    </div>
                    <?php
endforeach; ?>
                </div>
            </div>
        </button>
    </div>
    <div class="resource-text large-5 flex-container flex-dir-column align-center align-middle padding-1 large-padding-2 xlarge-padding-3">
        <div class="metadata margin-bottom-1 separator-center">
        <?php $showTitleOption = $this->showTitleOption; ?>
            <?php if ($showTitleOption == "item_title"): ?>
            <h2><?php echo $item->displayTitle(); ?></h2>
            <?php elseif ($showTitleOption == "file_name"): ?>
            <h2><?php echo $media->displayTitle(); ?></h2>
            <?php endif; ?>
        </div>
        <div class="text">
            <?= $html ?>
            <?php
            $identifier = $item->value("dcterms:identifier");
            if ($identifier): ?>
            <h2 class="h4"><small><?php echo "Ref. " . $identifier; ?></small></h2>
            <?php endif;
            ?>
        </div>
        <div class="learn-more">
            <h2 class="button large warning"><?php echo $item->link("View full item"); ?></h2>
        </div>
    </div>
</div>
