<?php
$escape = $this->plugin('escapeHtml');
$stylesheet = $this->themeSetting('stylesheet');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
if (isset($stylesheet)) {
    $this->headLink()->prependStylesheet($this->assetUrl("css/$stylesheet.css"));
} else {
    $this->headLink()->prependStylesheet($this->assetUrl('css/default.css'));
}
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('css/uom-header.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/uom-footer.css'));
$this->headScript()->prependFile($this->assetUrl('vendor/foundation/foundation.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();

$navLayout = ($this->themeSetting('nav_layout')) ? $this->themeSetting('nav_layout') : 'dropdown';
$this->htmlElement('body')->appendAttribute('class', $navLayout . '-menu');
if ($userBar) {
    $this->htmlElement('body')->appendAttribute('class', 'user-bar');
}

$banner = $this->themeSettingAssetUrl('banner');
$bannerWidth = ($this->themeSetting('banner_width')) ? $this->themeSetting('banner_width') : '';
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_', '-', $this->themeSetting('banner_position')) : 'center';
$logo = $this->themeSettingAssetUrl('logo');
if ($logo) :
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <style>
            .banner {
                height: <?php echo ($bannerHeight !== '') ? $bannerHeight : 'auto' ?>;
                align-items: <?php echo $bannerPosition; ?>;
            }
        <?php if ($bannerHeightMobile !== '') : ?>
            @media screen and (max-width:640px) {
                .banner {
                    height: <?php echo $bannerHeightMobile; ?>;
                }
            }
        <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    
        <div id="offCanvas" class="off-canvas position-left" data-off-canvas>
            <?php echo $site->publicNav()->menu()->setPartial('common/foundation-navigation.phtml')->renderPartialWithParams(['layout' => 'vertical']); ?>
            <div class="search">
                <?php echo $this->partial('common/search-form'); ?>
            </div>
        </div>
        <div class="off-canvas-content" data-off-canvas-content>
            <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
            <?php echo $userBar; ?>
            <header>
                <?php if ($navLayout == 'vertical') : ?>
                <?php echo $this->partial('common/header-vertical'); ?>
                <?php else : ?>
                <?php echo $this->partial('common/header-dropdown'); ?>
                <?php endif; ?>
                <?php if ($banner) : ?>
                <div class="banner <?php echo $bannerWidth; ?>">
                    <img src="<?php echo $this->themeSettingAssetUrl('banner'); ?>" title="Banner">
                </div>
                <?php endif; ?>
            </header>
            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>
            <footer class="footerContainer">							
                            <div class="row tripleVertPadding">
                                
                                <div class="eightcol">
                                    <div class="footerLogos">
                        
                                        <img src="https://www.library.manchester.ac.uk/assets/images/design/national-research-libraries.png" height="63" alt="National Research Libraries">											
                                        <p>The University of Manchester Library is one of five National Research Libraries</p>
                        
                                    </div>
                                </div>
                                
                                <div class="fourcol last">
                                    <h2>Connect with us</h2>
                                    <ul class="inlineList footer-socialIcons">
                                        
                                        <li><a href="https://www.facebook.com/pages/The-University-of-Manchester-Library/25777209922">
                                            <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-facebook-large.png" width="40" height="40" data-original="/assets/images/design/icon-facebook-large.png" alt="Facebook page for The University of Manchester Library">
                                            <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-facebook-large.png" width="40" height="40" alt="Facebook page for The University of Manchester Library"></noscript>
                                            </a>
                                        </li>
                                        <li><a href="https://twitter.com/UoMLibrary">
                                            <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-twitter-large.png" width="40" height="40" data-original="/assets/images/design/icon-twitter-large.png" alt="Twitter page for The University of Manchester Library">
                                            <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-twitter-large.png" width="40" height="40" alt="Twitter page for The University of Manchester Library"></noscript>
                                            </a>
                                        </li>
                                        <li><a href="https://www.instagram.com/uomlibrary/">
                                            <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-instagram.png" width="40" height="40" data-original="/assets/images/design/icon-instagram.png"  alt="Instagram page for The University of Manchester Library">
                                            <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-instagram.png" width="40" height="40" alt="Instagram page for The University of Manchester Library"></noscript>
                                            </a>
                                        </li>
                                        <li><a href="https://www.youtube.com/user/UoMLibrary">
                                            <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-youtube-large.png" width="40" height="40" data-original="/assets/images/design/icon-youtube-large.png"  alt="YouTube page for The University of Manchester Library">
                                            <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-youtube-large.png" width="40" height="40" alt="YouTube page for The University of Manchester Library"></noscript>
                                            </a>
                                        </li>
                                        <li><a href="https://www.linkedin.com/showcase/the-university-of-manchester-library">
                                            <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-linkedin.png" width="40" height="40" data-original="/assets/images/design/icon-linkedin.png"  alt="LinkedIn page for The University of Manchester Library">
                                            <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-linkedin.png" width="40" height="40" alt="LinkedIn page for The University of Manchester Library"></noscript>
                                            </a>
                                        </li>													
                                    </ul>
                                </div>
                            </div>
                            
                            <hr>
                                
                            <div class="row singleVertPadding">
                                <div class="twelvecol">
                                    <ul class="inlineList">
                                        <li><a href="https://www.manchester.ac.uk/disclaimer/">Disclaimer</a> /</li>
                                                    <li><a href="https://www.manchester.ac.uk/discover/privacy-information/data-protection/">Data Protection</a> /</li>
                                                    <li><a href="https://www.manchester.ac.uk/copyright/">Copyright notice</a> /</li>
                                                    <li><a href="https://www.library.manchester.ac.uk/accessibility/library-help/">Web accessibility</a> /</li>
                                                    <li><a href="https://www.manchester.ac.uk/discover/privacy-information/freedom-information/">Freedom of information</a> /</li>
                                                    <li><a href="https://www.manchester.ac.uk/discover/governance/charitable-status/">Charitable status</a> /</li>
                                      
                                        <li>Royal Charter Number: RC000797</li>
                                    </ul>
                                </div>
                            </div>
                           
                        </footer>
        </div>
        <script>
          $(document).foundation();
        </script>
    </body>
</html>
