<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$stylesheet = $this->themeSetting('stylesheet');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
if (isset($stylesheet)) {
    $this->headLink()->prependStylesheet($this->assetUrl("css/$stylesheet.css"));
} else {
    $this->headLink()->prependStylesheet($this->assetUrl('css/seafoam.css'));
}
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400&display=swap');
$this->headScript()->prependFile($this->assetUrl('vendor/foundation/foundation.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/langselect.js'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$this->jsTranslate();
$userBar = $this->userBar();

$navLayout = ($this->themeSetting('nav_layout')) ? $this->themeSetting('nav_layout') : 'dropdown';
$this->htmlElement('body')->appendAttribute('class', $navLayout . '-menu');
if ($userBar) {
  $this->htmlElement('body')->appendAttribute('class', 'user-bar');
}

$banner = $this->themeSettingAssetUrl('banner');
$bannerWidth = ($this->themeSetting('banner_width')) ? $this->themeSetting('banner_width') : '';
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html class="no-js"'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <style>
            .banner {
                height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
                background-image: url(<?php echo $this->themeSettingAssetUrl('banner'); ?>);
                background-position: <?php echo $bannerPosition; ?>;
            }
        <?php if ($bannerHeightMobile !== ''): ?>
            @media screen and (max-width:640px) {
                .banner {
                    height: <?php echo $bannerHeightMobile; ?>;
                }
            }
        <?php endif; ?>
        </style>
        <!-- Google Tag Manager --> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-MTKP79D'); </script> <!-- End Google Tag Manager -->
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <!-- Google Tag Manager (noscript) -->
            <noscript><iframe src=https://www.googletagmanager.com/ns.html?id=GTM-MTKP79D height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript> 
        <!-- End Google Tag Manager (noscript) -->
        <div id="offCanvas" class="off-canvas position-left" data-off-canvas>
            <?php echo $site->publicNav()->menu()->setPartial('common/foundation-navigation.phtml')->renderPartialWithParams(['layout' => 'vertical']); ?>
        </div>
        <div class="off-canvas-content" data-off-canvas-content>
            <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
            <?php echo $userBar; ?>
            <header>
                <?php if ($navLayout == 'vertical'): ?>
                <?php echo $this->partial('common/header-vertical'); ?>
                <?php else: ?>
                <?php echo $this->partial('common/header-dropdown'); ?>
                <?php endif; ?>
            </header>
            <?php if ($banner && ($navLayout == 'dropdown')): ?>
            <div class="banner <?php echo $bannerWidth; ?>"><img src="<?php echo $this->themeSettingAssetUrl('banner'); ?>" title="Banner" role="presentation" aria-hidden="true"></div>
            <?php endif; ?>
            <div id="content" role="main">
                <?php if ($banner && ($navLayout == 'vertical')): ?>
                <div class="banner <?php echo $bannerWidth; ?>"><img src="<?php echo $this->themeSettingAssetUrl('banner'); ?>" title="Banner" role="presentation" aria-hidden="true"></div>
                <?php endif; ?>
                <?php echo $this->content; ?>
            </div>
            <?php 
            $poweredByOmekaS = "Powered by Omeka S"; 
            $footerContent = $this->themeSetting('footer');
            ?>
            <?php if ($footerContent && (strpos($footerContent, $poweredByOmekaS) === false)): ?>
                <footer>
                    <?php echo $footerContent; ?>
                </footer>
                <?php else: ?>
                <footer class="footerContainer full-width">							
                    <div class="grid-x grid-padding-x grid-container padding-vertical-3">                        
                        <div class="cell small-6 medium-4 padding-left-1 padding-bottom-1">
                            <div class="footerLogos">
                
                                <img src="https://www.library.manchester.ac.uk/assets/images/design/national-research-libraries.png" height="63" alt="National Research Libraries">											
                                <p>The University of Manchester Library is one of five National Research Libraries</p>
                
                            </div>
                        </div>
                        <div class="cell small-6 medium-4 padding-left-1 medium-padding-right-1 padding-bottom-1">
                            <h3>Get in touch</h3>
                            <p><a href="https://forms.library.manchester.ac.uk/public/form/649ac12b3917fcd3e2918ef4">In our efforts to improve this site, we welcome your thoughts, questions, and feedback.</a></p>
                        </div>
                        <div class="cell small-12 medium-4 padding-left-1 medium-padding-right-1">
                            <h3>Connect with us</h3>
                            <ul class="inlineList footer-socialIcons">
                                
                                <li><a href="https://www.facebook.com/pages/The-University-of-Manchester-Library/25777209922">
                                    <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-facebook-large.png" width="40" height="40" data-original="/assets/images/design/icon-facebook-large.png" alt="Facebook page for The University of Manchester Library">
                                    <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-facebook-large.png" width="40" height="40" alt="Facebook page for The University of Manchester Library"></noscript>
                                    </a>
                                </li>
                                <li><a href="https://twitter.com/UoMLibrary">
                                    <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-twitter-large.png" width="40" height="40" data-original="/assets/images/design/icon-twitter-large.png" alt="Twitter page for The University of Manchester Library">
                                    <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-twitter-large.png" width="40" height="40" alt="Twitter page for The University of Manchester Library"></noscript>
                                    </a>
                                </li>
                                <li><a href="https://www.instagram.com/uomlibrary/">
                                    <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-instagram.png" width="40" height="40" data-original="/assets/images/design/icon-instagram.png"  alt="Instagram page for The University of Manchester Library">
                                    <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-instagram.png" width="40" height="40" alt="Instagram page for The University of Manchester Library"></noscript>
                                    </a>
                                </li>
                                <li><a href="https://www.youtube.com/user/UoMLibrary">
                                    <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-youtube-large.png" width="40" height="40" data-original="/assets/images/design/icon-youtube-large.png"  alt="YouTube page for The University of Manchester Library">
                                    <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-youtube-large.png" width="40" height="40" alt="YouTube page for The University of Manchester Library"></noscript>
                                    </a>
                                </li>
                                <li><a href="https://www.linkedin.com/showcase/the-university-of-manchester-library">
                                    <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-linkedin.png" width="40" height="40" data-original="/assets/images/design/icon-linkedin.png"  alt="LinkedIn page for The University of Manchester Library">
                                    <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-linkedin.png" width="40" height="40" alt="LinkedIn page for The University of Manchester Library"></noscript>
                                    </a>
                                </li>													
                            </ul>
                        </div>
                    </div>               
                    <hr class="full-width">                    
                    <div class="grid-x grid-container padding-bottom-1">
                        <ul class="inlineList">
                            <li><a href="https://www.manchester.ac.uk/disclaimer/">Disclaimer</a> /</li>
                                        <li><a href="https://www.manchester.ac.uk/discover/privacy-information/data-protection/">Data Protection</a> /</li>
                                        <li><a href="https://www.manchester.ac.uk/copyright/">Copyright notice</a> /</li>
                                        <li><a href="https://www.library.manchester.ac.uk/accessibility/manchester-digital-exhibitions/">Web accessibility</a> /</li>
                                        <li><a href="https://www.manchester.ac.uk/discover/privacy-information/freedom-information/">Freedom of information</a> /</li>
                                        <li><a href="https://www.manchester.ac.uk/discover/governance/charitable-status/">Charitable status</a> /</li>
                            
                            <li>Royal Charter Number: RC000797</li>
                        </ul>
                    </div>               
                </footer>
            <?php endif; ?>
        </div>
        <script>
          $(document).foundation();
        </script>
    </body>
</html>
